### ISSUE TITLE
Link should allow arbitrary content

### ISSUE THREAD

**Issue by benzen** [phoenixframework/phoenix_html#104]
With Link function we can creat easely née link we text inside the a.
But we cant do it easely with arbitrary content like a button. Unless we put the button définition in a string.

It would be nice to allow the same syntaxe for the link as for the if tag.

**Comment by chrismccord** [comment]
You can do this today with the do/end form of `link`:
https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/link.ex#L25-L28
