### ISSUE TITLE
pass data into link post

### ISSUE THREAD

**Issue by benzen** [phoenixframework/phoenix_html#105]
Reading https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html

It's not clear if we can send data in the post.
I assume it's possible using the :form key, but not much is explain about it.

**Comment by josevalim** [comment]
The only data you can pass is through the URL. If you need to pass more data, than consider defining the form yourself, as that's likely going to be clearer.

**Comment by benzen** [comment]
As you proposed I implement it myself.
Still I think that the data key in the
Option list should hold data to pass into the form as hidden fields
