### ISSUE TITLE
Rebar3 detected a lock file from a newer version

### ISSUE THREAD

**Issue by satb** [phoenixframework/phoenix_html#106]
During compilation, I am seeing this output. What is this and how can we update to rebar3. Sorry, if this is a naive question. I am new to the entire elixir/phoenix/erlang ecosystem.

On Ubuntu 16.04, with erlang 19 and elixir 1.3.2

```
Generated plug app
==> phoenix_html
Compiling 8 files (.ex)
Generated phoenix_html app
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Rebar3 detected a lock file from a newer version. It will be loaded in compatibility mode, but important information may be missing or lost. It is recommended to upgrade Rebar3.
===> Compiling relx
.....
.....
....
```

**Comment by satb** [comment]
Sorry, it looks like it belongs somewhere else and not in this repo since rebar3 is a build tool. For some reason it always dumps those lines right on/after phoenix_html. But I am not sure where or why it is coming from.

**Comment by josevalim** [comment]
@satb `mix deps` may tell you which dependency is coming after `phoenix_html` and if it uses rebar. It is going to be an Erlang dependency most likely.

Usually those problems mean you are using an older rebar3 version. I would recommend to remove any rebar you may have in your path (you can find it  with `which rebar` or `which rebar3`) and then run `mix local.rebar` to update the rebar used by mix.

**Comment by satb** [comment]
@josevalim - Thank you. But there isn't any other version of rebar.

```
root@e1ee27ec2aaf:/apps# ls -l ~/.mix/
archives/ rebar     rebar3

root@e1ee27ec2aaf:/apps# which rebar
root@e1ee27ec2aaf:/apps# which rebar3
root@e1ee27ec2aaf:/apps#
```

mix deps returns this:

```
...
* mime 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (mime) 05c39385
  ok
* plug 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (plug) 496bef96
  ok
* phoenix_html 2.6.2 (Hex package) (mix)
  locked at 2.6.2 (phoenix_html) 944a5e58
  ok
* relx 3.20.0 (Hex package) (rebar3)
  locked at 3.20.0 (relx) b515b831
  ok
* exrm 1.0.8 (Hex package) (mix)
  locked at 1.0.8 (exrm) 5aa8990c
  ok
...
```

So relx is wanting something that is out of date somehow?

**Comment by josevalim** [comment]
It seems so. Did you run `mix local.rebar` to update your local rebar? Try `mix local.rebar` and then `rm -rf _build deps`.

**Comment by satb** [comment]
Its a new docker container launched everytime. The docker file itself is doing this to create the image so it doesn't have to be done everytime the container is launched:

mix local.hex --force \
mix local.rebar --force

Once inside the container if I run the

mix local.rebar
/root/.mix/rebar already exists, overwrite? [Yn] Y
* creating /root/.mix/rebar
/root/.mix/rebar3 already exists, overwrite? [Yn] Y
* creating /root/.mix/rebar3

rm -rf _build deps didn't do much to help because. I am still looking to find a clue.

**Comment by josevalim** [comment]
Ok, I checked and it seems the message is OK. The projects are actually using an older lock file version, so you have the latest rebar but the projects have outdated lock files. Your only option is to use a more recent project version if there is one. Otherwise you can safely ignore it. You may want to provide this as feedback to them if the message is/was confusing. :)

**Comment by satb** [comment]
Thanks so much for confirming its not a harmful error. By "them" you are referring to the relx repo? Is it this file? - https://github.com/erlware/relx/blob/master/relx.config
