### ISSUE TITLE
Nil params are ignored on form re-render

### ISSUE THREAD

**Issue by sevenseacat** [phoenixframework/phoenix_html#11]
Due to this line here:

https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L805

If an empty value is submitted, scrubbed to nil, and then the form is re-rendered, the nil value is ignored due to it's falsiness and the original value used instead.

Presume it should be like "if the field exists in the params, use it, else go back to the original value".

**Comment by josevalim** [comment]
You are right. I thought it could never happen but with scrub_params in the controller, it is certainly an issue.

**Comment by josevalim** [comment]
@sevenseacat can you please send a pull request? I believe we can use something like `Map.fetch`. We don't need to test all inputs also, I think just text_input would be fine. :) Thank you!

**Comment by sevenseacat** [comment]
will look at doing so this evening :)
