### ISSUE TITLE
Document how to receive multiple files with file_input

### ISSUE THREAD

**Issue by Fahrradflucht** [phoenixframework/phoenix_html#114]
The docs of `file_input` don't mention anything about `multiple` which led me to thinking that just adding `multiple: true` should do the trick.

Turns out you also have to add `name: "files[]"` or at least something with `[]` at the end to receive more then one file.

It would be great if this would be documented. I don't really get the cause of this so if someone could point that out, this would be great as well.

**Comment by josevalim** [comment]
@Fahrradflucht could you please either send a pull request that improves the docs or add support for the `multiple: true` option that automatically appends to the end of the name? Thank you!
