### ISSUE TITLE
FormData option for link / button helper

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_html#118]
It would be quite nice, if one could add arbitrary formdata to a link/button form. E.g. I've a model for checklists and one for it's usage (so a checklist has many usages). I'd like to link directly from the checklist index page to the create action of the usage controller filling the checklist_id via the link form.

**Comment by josevalim** [comment]
@LostKobrakai can you please provide a little bit more information? Maybe a code sample on what you would like to write and what you expect as output? Thank you.

**Comment by LostKobrakai** [comment]
```elixir
<%= form_for ChecklistStatus.changeset(%ChecklistStatus{}, %{checklist_id: checklist.id}), checklist_status_path(@conn, :create), [method: "create"], fn f -> %>
    <%= hidden_input f, :checklist_id %>
    <a class="btn btn-default btn-xs" data-submit="parent" href="#" rel="nofollow">Fill</a>
<% end %>
```

Basically this and now that I've the solution I feel like it's much cleaner anyway to explicitly use a real form and all it's automatisms.
