### ISSUE TITLE
Improve documentation for content_tag/3

### ISSUE THREAD

**Issue by pcewing** [phoenixframework/phoenix_html#120]
There is currently no documentation for the `Phoenix.HTML.content_tag/3` function, which is actually really handy. In Programming Phoenix, it's used to set up some data attributes as such:
```elixir
<%= content_tag :div, id: "video", data: [id: @video.id, player_id: player_id(@video)] do %>
<% end %>
```

Most of the attributes like `:height` and `:width` are self-explanatory; however, it would still be nice to know what attributes are supported/how to use them in cases like `:data` where usage isn't immediately obvious.

(Somewhat related, the third parameter is incorrectly named `attrs`; it should be `content` to be consistent with the other functions.)

I'd be happy to help out with this :)

**Comment by chrismccord** [comment]
There is documentation here:
https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/tag.ex#L50-L62

If you think this can be approved, please send a PR!

**Comment by pcewing** [comment]
Aha! I didn't notice one of the examples above actually uses the attributes parameter. I'll still see if I can clarify the docs a bit and I'll fix the parameter names for content_tag/3.

**Comment by chrismccord** [comment]
Great! Please send a PR when ready.
