### ISSUE TITLE
image_tag?

### ISSUE THREAD

**Issue by drapergeek** [phoenixframework/phoenix_html#129]
Would you be interested in an `image_tag` function? I'm imagining a thin wrapper around content tag that takes the first argument as a binary and sets the `src`. This seems like a pretty common use case to support.

I'm happy to implement it just didn't want to do the work if you weren't interested.

**Comment by sevenseacat** [comment]
what benefit does that offer over a plain HTML `img` tag?

**Comment by josevalim** [comment]
If we introduce something like that, possibly the only benefit would be to automatically call `static_path` on it so we get proper expire headers I am unsure. `<tag>` and `tag :img, src: "foo"` are OK and you can always provide `img_tag` in your apps?

**Comment by drapergeek** [comment]
Convenience is the primary reason.

I think that reading
```
<%= img(@user.avatar) %>
```

Is nicer than

```
<img src="#{@user.avatar}">
```
and that becomes even more clear when you start adding classes with conditionals.


>you can always provide img_tag in your apps?

I agree with this completely and so far, that's what I've been doing but I think the same thing could be said for a lot of other functions in this library! I imagine the goal of this library is to make writing HTML in Elixir easier and I think this helps. It's a small function that while you could very easily write it in your own apps, I don't like duplicating things across codebases and having it available for people new to the framework is also nice.

No hard feelings if you disagree, that's why I asked first!

**Comment by josevalim** [comment]
I just realized a helper could also be helpful in regards to HTML safety, so let's add `img_tag(src, opts)`. PR please? :)
