### ISSUE TITLE
nested object name

### ISSUE THREAD

**Issue by ellisae** [phoenixframework/phoenix_html#133]
I have a problem with setting nested object name

Here is an example with checkbox element:

`> Form.form_for %Plug.Conn{}, "get", [as: "filter"], fn f -> Form.checkbox f, :"nested[entry][name]" end`
this will generate input with `name="filter[nested[entry][name]]"` what is incorrect
because it gives me `%{"_utf8" => "✓", "filter" => %{"nested[entry" => %{"name]" => "false"}}}` in my parameters.

To be able to get correct nested object in parameters I have to set correct element name:
`name="filter[nested][entry][name]"`

and to get this I do the following:
`> Form.form_for %Plug.Conn{}, "get", [as: "filter"], fn f -> Form.checkbox f, :"nested][entry][name" end`

this looks weird but it gives me correct element name: `filter[nested][entry][name]` in my form and correct object in my params:
`%{"_utf8" => "✓", "filter" => %{"nested" => %{"entry" => %{"name" => "false"}}}`

**Comment by josevalim** [comment]
Yo can either:

1. pass [as: "filter[nested][entry]"] to `form_for`
2. use `inputs_for` to create a group of nested inputs
3. pass the `:name` option to `checkbox`

**Comment by ellisae** [comment]
thank you
passing name option explicitly for input element 
`name: "filter[nested][entry][name]"`
solves my problem
