### ISSUE TITLE
`select` can't have a labels with non-english letters

### ISSUE THREAD

**Issue by asiniy** [phoenixframework/phoenix_html#137]
elixir -v `1.3.4`
phoenix_html `2.9.2`
phoenix `1.2.1`

non-english letters (I tested with Arabian and Russian alphabet) doesn't look to be working as select labels. EEX:

``` elixir
        <%= select :filter, :state, [
          "حر": "arabian",
          "Хосе, ты пиздат!": "russian"
        ] %>
```

Everything is broken at compilation level. An exception:

``` elixir
** (ArgumentError) argument error
    :erlang.binary_to_atom("حر", :utf8)
    (elixir) src/elixir_parser.yrl:512: :elixir_parser.yeccpars2_93/7
    (elixir) /usr/lib/erlang/lib/parsetools-2.1.1/include/yeccpre.hrl:57: :elixir_parser.yeccpars0/5
    (eex) lib/eex/compiler.ex:34: EEx.Compiler.generate_buffer/4
    (eex) lib/eex/compiler.ex:41: EEx.Compiler.generate_buffer/4
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    web/views/task_view.ex:1: Oblako.TaskView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
The value will work, by the way:

``` elixir
        <%= select :filter, :state, [
          "hehe": "Хосе, всё круто", # this works nice
        ] %>
```

**Comment by asiniy** [comment]
Oh, the problem is in the whole elixir (it looks like so). Just in iex:

```
["абаба": "bcbc"]
** (ArgumentError) argument error
             :erlang.binary_to_atom("абаба", :utf8)
    (elixir) src/elixir_parser.yrl:512: :elixir_parser.yeccpars2_93/7
    (elixir) /usr/lib/erlang/lib/parsetools-2.1.1/include/yeccpre.hrl:57: :elixir_parser.yeccpars0/5
```

It looks like I can't do that in elixir, but I still need russian letters as labels... Is it a bug or feature?

**Comment by asiniy** [comment]
This is a problem of the whole [erlang.binary_to_atom](http://erlang.org/doc/man/erlang.html#binary_to_atom-2)

> binary_to_atom(Binary, utf8) fails if the binary contains Unicode characters > 255. In a future release, such Unicode characters can be allowed and binary_to_atom(Binary, utf8) does then not fail. For more information about Unicode support in atoms, see the note on UTF-8 encoded atoms in section "External Term Format" in the User's Guide.

``` elixir
%{
  "абв": "ced"
}
```

gives the same error message

**Comment by michalmuskala** [comment]
Only latin1 characters are supported in atoms right now (this is an Erlang limitation).

I'm pretty sure, you can pass a list of pairs where both key and value are binaries:
```elixir
<%= select :filter, :state, [
  {"حر", "arabian"},
  {"Хосе, ты пиздат!", "russian"}
] %>
```

**Comment by asiniy** [comment]
Argghh, @michalmuskala you're right. Thanks!
My PR is not needed anymore. Will close it
