### ISSUE TITLE
I can select wrong dates like `31 of February` in `date_select`

### ISSUE THREAD

**Issue by asiniy** [phoenixframework/phoenix_html#139]
I think there should be a javascript workaround for that. This behavour looks unprofessional

![screenshot from 2017-01-14 08 38 20](https://cloud.githubusercontent.com/assets/1296472/21952752/4cc36206-da3d-11e6-94a8-5c67210d6d5e.png)

**Comment by josevalim** [comment]
You don't have to use select_datetime. For example, you can use any of the libraries that provide a modal for datetime, for example, or even the datetime input from HTML 5. The current option is useful for those who cannot rely on JavaScript or HTML 5 inputs.
