### ISSUE TITLE
Populating form fields on update resource

### ISSUE THREAD

**Issue by ventsislaf** [phoenixframework/phoenix_html#14]
It can be reproduced using the code from generators. Run `mix phoenix.gen.model User users name:string`. Then create one user. Try editing the user and submit empty name… you’ll get the expected error `Name can't be blank` but the field itself in the form will be populated with the old value instead of being empty.

![screen shot 2015-06-14 at 16 28 03](https://cloud.githubusercontent.com/assets/620167/8149233/0b1a6b4e-12b4-11e5-8bc2-1cbba10145f7.png)

**Comment by chrismccord** [comment]
I believe this was fixed in #12. Please try the latest release and re-open if the issue persists. Thanks!
