### ISSUE TITLE
[Proposing] Use of a hyphen to separate words in ID names

### ISSUE THREAD

**Issue by anronin** [phoenixframework/phoenix_html#150]
Hello! I propose to consider the use of a hyphen to separate words in ID names for inputs and label or add something like a set of options to the `form_for` and `input_for`:

- "underscore": Lowercase and underscore-separated.
- "dash": Lowercase and separated by hyphens.
- "camel": camelCase.
- "bem": The BEM (block, element, modifier) syntax. (not sure about this)

I know that there is no consensus on this, but at least large companies and a significant number of developers advised to use a hyphen in ID names and the use of the underscore is the least popular option, and if there are no objections then i'll try to make PR in near time. Wdyt?

**Comment by josevalim** [comment]
Unfortunately this change would be backwards incompatible, so we don't plan to incorporate it.
