### ISSUE TITLE
Use gettext for months

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix_html#152]
The [months](https://github.com/phoenixframework/phoenix_html/blob/72b5c1c21aabb7e3236dfc24d2a987bc2813f124/lib/phoenix_html/form.ex#L1121-L1134) in `Phoenix.HTML.Form` are only available in English and not translatable. I'm happy to open a PR but need a hint on how to use gettext outside of the Phoenix application.

**Comment by josevalim** [comment]
See #51. :) I will prioritize this when i am back from holidays.
