### ISSUE TITLE
phoenix_html.js does not handle clicks on children of <a> element anymore

### ISSUE THREAD

**Issue by dirkholzapfel** [phoenixframework/phoenix_html#164]
With the update to v2.10.1 the children element of `<a>` elements don't handle clicks anymore, because the javascript does not take parent elements into account.

I am not sure if this behaviour is intended or a bug.

This worked on v.2.9.3:

```eex
<%= link to: the_path,
         method: :delete,
         data: [confirm: gettext("Really delete?")] do %>
  <img src="the_src">
<% end %>
```

**Comment by josevalim** [comment]
Thank you for the report! I have pushed a fix here: 8fe1fa32d7a321ba34c55a7d6659fa7102195189

Can you please try master and let me know if it works? You will likely have to remove node_modules for the new version to come up.

Once you verify it, I can ship 2.10.2.

**Comment by dirkholzapfel** [comment]
Thank you very much for the quick fix, @josevalim ! It works fine.

**Comment by dirkholzapfel** [comment]
fixed with https://github.com/phoenixframework/phoenix_html/releases/tag/v2.10.2
