### ISSUE TITLE
ArgumentError when supplying Keyword list as option to `button` since 2.10.0

### ISSUE THREAD

**Issue by Frost** [phoenixframework/phoenix_html#165]
I have two questions regarding the underlying form generated by the `button` helper function.

In my code, I have this:

```elixir
button(
  class: "btn helpful__button helpful__button--yes",
  role: "button",
  to: <snip>,
  method: :post,
  form: [
    class: "helpful__form",
    role: "presentation"
  ] ++ Keyword.get(options, :form_opts, [])
)
```

That class name and the role are there to help with non-mouse navigation.

Up and until version 2.9.3, this resulted in the following HTML code:

```
<form action="..." class="helpful__form" method="post" role="presentation">
  <input name="_csrf_token" type="hidden" value="...">
  <button class="btn helpful__button helpful__button--yes" role="button" type="submit">...</button>
</form>
```

Since version 2.10.0, however, this generates the following error:

```
    5) test show/2 works without category param (Knowledgebase.PublicGuideControllerTest)
       test/controllers/public_guide_controller_test.exs:43
       ** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: {:class, "helpful__form"}
       stacktrace:
         (phoenix_html) lib/phoenix_html/safe.ex:80: Phoenix.HTML.Safe.List.to_iodata/1
         (phoenix_html) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
         (phoenix_html) lib/phoenix_html/tag.ex:94: anonymous fn/2 in Phoenix.HTML.Tag.tag_attrs/1
         (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
         (phoenix_html) lib/phoenix_html/tag.ex:93: Phoenix.HTML.Tag.tag_attrs/1
         (phoenix_html) lib/phoenix_html/tag.ex:88: Phoenix.HTML.Tag.content_tag/3
         (knowledgebase) lib/knowledgebase/web/templates/public_guide/vote_buttons.html.eex:4: Knowledgebase.Web.PublicGuideView."vote_buttons.html"/1
```

Since I cannot find any notice of any breaking changes in the [CHANGELOG entry](https://github.com/phoenixframework/phoenix_html/blob/master/CHANGELOG.md#v2100-2017-07-21) for 2.10.0, I wonder if this is intentional or if anything else changed that I missed.

Another slightly related thing I noticed is that [this commit that landed in 2.10.2](https://github.com/phoenixframework/phoenix_html/commit/0e017552cf2f782885192e892d38ecb5142f8e36) seems to remove the `form` option to the `button` tag entirely. This also was not mentioned in the CHANGELOG. Instead the form tag seems to be generated in JavaScript. Does this mean that I can no longer style the form tag generated by the `button` element?

Can I change my code to support this change my call to the `button` function to generate the code I want? Or do I have to do this in some other way from now on?

**Comment by josevalim** [comment]
@Frost that was a hindsight on my part, apologies. We no longer generate nested forms and instead we moved it to javascript. Therefore the `:form` option has no effect. I will make sure to discard it and log if appropriate. I will also update the CHANGELOG.

**Comment by Frost** [comment]
@josevalim Thank you for the information! 

I will just have to tell our resident UI expert to style the new, generated code instead, once he's back from vacation. 😄 

Should I leave this issue open or close it?

**Comment by josevalim** [comment]
Open please. :)

**Comment by josevalim** [comment]
CHANGELOG has been updated.
