### ISSUE TITLE
Feature request: javascript_include_tag and stylesheet_include_tag

### ISSUE THREAD

**Issue by amedeedaboville** [phoenixframework/phoenix_html#168]
I'm porting a large Rails app over to Phoenix and Rails has these `javascript_include_tag` and  `stylesheet_include_tag` convenience functions, which seem nice to have.

Would they be a good fit for the `Phoenix.HTML.Tag` module? I know they are simple wrappers around `<% <script ...> %>` et al but they feel nice to use. I also noticed this module has functions for making a form as well as an `img_tag` function, so they look like they would fit here.

Something like: (just spitballing here)
```
def javacript_include_tag(src, opts \\ []) do
  content_tag(:script, "", Keyword.put_new(opts, :src, src))
end

def stylesheet_include_tag(href, opts \\ []) do
  params = opts
          |> Keyword.put(:rel, "stylesheet")
          |> Keyword.put_new(:href, href)
  content_tag(:link, "",  params)
end
```

**Comment by josevalim** [comment]
I am a bit torn on those two because  HTML is already a declarative language. So we need to balance the benefits of introducing it with what we hide behind the function.

I would see benefit on those functions if we could automatically call static_path on those arguments - which is something I think most users would forget to do anyway.

**Comment by alizain** [comment]
> I would see benefit on those functions if we could automatically call static_path on those arguments

Yes! I usually make a small module like this:

```elixir
defmodule VolunteerWeb.StaticHelpers do
  use Phoenix.HTML
  alias VolunteerWeb.Router.Helpers, as: RouterHelpers

  def script_tag(conn, path) do
    content_tag(:script, "", type: "text/javascript", src: RouterHelpers.static_path(conn, path))
  end

  def stylesheet_tag(conn, path) do
    tag(:link, rel: "stylesheet", href: RouterHelpers.static_path(conn, path))
  end
end
```

And use it like this:

```eex
<head>
    <%= StaticHelpers.stylesheet_tag(conn, "/css/admin/common.css") %>
</head>
```

**Comment by josevalim** [comment]
Closing this for now as I don't think the gain is that relevant and we will be including features soon that make it easier to interpolate things into HTML documents. Thanks!
