### ISSUE TITLE
Incorrect hidden_input for boolean.

### ISSUE THREAD

**Issue by jacekbogdanski** [phoenixframework/phoenix_html#171]
I am not sure if it's Ecto casting or Phoenix bug. Phoenix.HTML.Form.hidden_input for boolean field produces for false: 
```html
<input type="hidden" id="struct_field" name="struct[field]" value="" />
```
and for true:
```html
<input type="hidden" id="struct_field" name="struct[field]" value="value" />
```
It gives casting validation error when creating changeset from params. Ecto can't cast string "value" to true. It's fine for "true" string.

**Comment by josevalim** [comment]
That's the semantics of HTML attributes where the is not really a "true", but the key is repeated, such `disabled="disabled"`. If you want "true" / "false", then it needs to be cast to a string.

**Comment by jacekbogdanski** [comment]
Thanks for fast reply. That's right but it seems inconsistent with ecto. Shouldn't it work out of the box? Now we have to manually cast booleans with ecto by custom type or provide "true" / "false" for hidden_input.

**Comment by josevalim** [comment]
@jacekbogdanski we need to handle it here rather. The best solution is probably to call html_escape on the :value attribute inside generic_input.
