### ISSUE TITLE
why does submit not follow the same pattern as text_input and other helpers

### ISSUE THREAD

**Issue by daya** [phoenixframework/phoenix_html#179]
https://github.com/phoenixframework/phoenix_html/blob/4f562e2367074da8b9a29822e2249ecfb8ceef42/lib/phoenix_html/form.ex#L606

I am a nood to Phoenix, but it seems odd to me that in this block only `submit` doesn't accept `form` as first argument while `text_input` and `password_input` do, is this an inconsistency or am I missing something??

```
<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>
```

**Comment by josevalim** [comment]
It doesn't accept one because it doesn't need one. :)

**Comment by daya** [comment]
@josevalim coming from Rails where `f.submit` is used it actually makes sense to use `form` as first argument to `submit` hence my comment about inconsistency ... its just easier to follow patterns than exceptions to patterns

**Comment by josevalim** [comment]
I can see the argument for consistency but I can also see the argument for making it simpler, if it can be simpler. Since that's how it works today, we plan to keep it that way. Thanks.
