### ISSUE TITLE
Use `html_escape_to_iodata` instead of `html_escape`?

### ISSUE THREAD

**Issue by mischov** [phoenixframework/phoenix_html#180]
Implementations of `Phoenix.HTML.Safe.to_iodata/1` use `Plug.HTML.html_escape/1`, which always returns a binary (calls `IO.iodata_to_binary/1`). 

It seems like it would be more appropriate to instead use `Plug.HTML.html_escape_to_iodata/1` which returns iodata.

Is there some reason `html_escape` is preferred to `html_escape_to_iodata`?

**Comment by josevalim** [comment]
@mischov definitely. Can you please send a pull request?

**Comment by josevalim** [comment]
Actually, I am on it. ;)

**Comment by mischov** [comment]
Ha, I was going to say no problem on the PR, but yeah... it's like 4 lines in HTML.Safe and MAYBE 1 line in the Engine. https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/engine.ex#L86
