### ISSUE TITLE
Cannot generate html5 boolean attribute using `tag` or `content_tag`

### ISSUE THREAD

**Issue by ijcd** [phoenixframework/phoenix_html#182]
I am working with the javascript libraries that are parsing the dom and looking for html5 boolean values in the name-only format (no value) to indicate boolean. I can't seem to figure out how to create that using `tag` or `content_tag`:

The boolean attribute styles are described here:

http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes

Current output:

```
iex(12)> Phoenix.HTML.safe_to_string Phoenix.HTML.Tag.content_tag(:p, "Hello", "checked": true)
"<p checked=\"checked\">Hello</p>"
```

Desired output:
```
iex(12)> Phoenix.HTML.safe_to_string Phoenix.HTML.Tag.content_tag(:p, "Hello", "checked": true)
"<p checked>Hello</p>"
```

Would you accept a patch that would adjust the output to be as above? You could still generate the current format using a normal string value for the attribute.

**Comment by josevalim** [comment]
Thanks @ijcd. I don' see a problem doing this change but I would like to know what is the browser support for boolean attributes (or HTML5). I think we should be covered but it would be good to sanity check. Can you please investigate and see if you find some information?

**Comment by ijcd** [comment]
Some discussion here:

https://stackoverflow.com/questions/4139786/what-does-it-mean-in-html-5-when-an-attribute-is-a-boolean-attribute

Ideally, the document generator as a whole could somehow be aware of the document doctype (html4, html5, xhtml, etc...) and generate tags appropriately. These functions are just a text emitter though, the function caller would have to be aware of when which form was appropriate when.

About 18 tests broken when I made the change locally. (the output tests for the form helper, etc.) so people might feel the effect if they encountered the default.

I don't see a lot of compatibility information about this specific feature, but since it is basic DOM stuff I would think the lack of information (caniuse.com, html4test.com, etc) means it is well supported.

I do note that the developer.mozilla.org docs show the naked use of "checked" in their examples:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

Since it is required for input validation, this older article indicates that at least parsing for the "required" boolean attribute has been on all browsers since Safari 9.5(the laggard):

https://developer.telerik.com/topics/web-development/cross-browser-html5-form-validation-finally-now/

I assume the dom parsing side was around much longer.

**Comment by ijcd** [comment]
I made a PR just in case. I was able to update the form, select, checkbox, and radio_button helpers to maintain the current output style for their boolean attributes(checked, selected, etc.)

https://github.com/phoenixframework/phoenix_html/pull/183

**Comment by josevalim** [comment]
Closing in favor of the PR. :)
