### ISSUE TITLE
Documentation for Form.select/4 is inconsistent

### ISSUE THREAD

**Issue by axelclark** [phoenixframework/phoenix_html#187]
The [documentation](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#select/4) for `Form.select/4` says "keyword lists - each keyword list is expected to have the keys `:value` and `:label`."

Later the example uses `:key` instead of `:label`
```
select(form, :role, [[key: "Admin", value: "admin", disabled: true],
                     [key: "User", value: "user"])
#=> <select id="user_role" name="user[role]">
    <option value="admin" disabled="disabled">Admin</option>
    <option value="user">User</option>
    </select>
```
The code expects `:key`
https://github.com/phoenixframework/phoenix_html/blob/9ee9b846748e9485027337cfa526f79be07ce23e/lib/phoenix_html/form.ex#L937

I can submit a pull request to update the documentation to `:key`, but `:label` seems more appropriate.

**Comment by josevalim** [comment]
@axelclark we should update the docs as changing the code would be a breaking change. Can you please send a PR for the docs?

**Comment by josevalim** [comment]
This has already been fixed in master, thank you.
