### ISSUE TITLE
Phoenix.HTML.Format.text_to_html/2 new line characters

### ISSUE THREAD

**Issue by sn3p** [phoenixframework/phoenix_html#190]
As per docs we can use [`text_to_html/2`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Format.html#text_to_html/2) to transform `\n\n` to paragraphs:

```
iex> text_to_html("Hello\n\nWorld") |> safe_to_string
"<p>Hello</p>\n<p>World</p>\n"
```

https://github.com/phoenixframework/phoenix_html/blob/0bb681d4e98b61a76dc03ff7a438a1fa64facd5d/lib/phoenix_html/format.ex#L42

Works perfectly, but in my case the text has new lines formatted as `\r\n\r\n`. This pattern is not recognised as double new line, and thus not split into paragraphs:

```
iex> text_to_html("Hello\r\n\r\nWorld") |> safe_to_string
"<p>Hello\r<br>\n\r<br>\nWorld</p>\n"
```

Is there a reason for not including this pattern?

From what I understand `\r\n` (Carriage Return & Line Feed) is used by Windows. 
But my text was written in a `textarea` (Chrome on macOS), and stored and fetched form Postgres (Unix).

---

_Newline characters that major platforms use:_

Platform | Line Break
-- | --
Windows | \r\n (Carriage Return & Line Feed)
Unix/Linux/MacOS X | \n (Line Feed)
MacOS 9 and earlier | \r (Carriage Return)

**Comment by josevalim** [comment]
Yeah, we should support both \r\n and \n. PR please?
