### ISSUE TITLE
button/link with :delete method?

### ISSUE THREAD

**Issue by sn3p** [phoenixframework/phoenix_html#192]
I'm trying to update phoenix_html from `2.9.0` to `2.10.5` and noticed for [`button`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#button/2) and [`link`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2) the `:form` option has been removed.

Before the update we used `button` to perform `:delete` actions. For example this would automatically wrap the button in a form element:

```ex
button("Delete", to: "/users/3/tasks/5", method: :delete, form: [data: [remote: true]])
```

So I need an alternative. One way would be rendering the form myself, or use [javascript](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2-javascript-dependency) to perform the action.

**What is considered best practice in this case?**

---

#### Using `link` with `method: :delete`

The [docs](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2-options) say:

> `:method` - the method to use with the link. In case the method is not :get, the link is generated _**inside the form**_ which sets the proper information. In order to submit the form, JavaScript must be enabled

When I try this (with javascript enabled) it doesn't render a form. Instead I get this output:

```ex
link("Delete", to: "/users/3/tasks/5", method: :delete)
#=> <a data-method="delete" data-to="/users/3/tasks/5" href="#" data-csrf="MHgDP..." rel="nofollow">Delete</a>
```

Clicking the link results in:
 
```
no route found for DELETE /users/3
```

**Is this a bug or am I doing something wrong?**

**Comment by josevalim** [comment]
We moved the creation of the form to javascript due to #151, so it should work as long as you make sure your javascript is up to date. Try removing the node_modules and compiling the JS again as mentioned in #167.

**Comment by sn3p** [comment]
Thanks for pointing that out, I overlooked the issues.

**Comment by sn3p** [comment]
@josevalim I tried clearing my depts and node_modules, but the problem persisted.  
Seems that there is a conflict between **`phoenix_html.js`** and **`jquery_ujs`** (dependency of [ex_turbolinks](https://github.com/imranismail/ex_turbolinks)).

### Test case

I've created a **[TEST APP](https://github.com/sn3p/phoenix_test)** to reproduce and demonstrate the problem. Feel free to check it out.

### The problem

[`link/2`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2) has the `method` option to send `:post` and `:delete` requests:

```ex
link("post",   to: "/things", method: :post)
link("delete", to: "/things", method: :delete)
```

But this conflict with Turbolinks. It seems `data-to="/things"` is ignored and instead it follows `href="#"`, causing errors like this:

```
No route found for POST / (PhoenixTestWeb.Router)
```

Not sure if this should be considered an issue of phoenix_html, but I hope this helps us find a solution. If you have suggestions please let me know!

(Related issue: [ex_turbolinks/issues/6](https://github.com/imranismail/ex_turbolinks/issues/6))

**Comment by AlmogRnD** [comment]
Has anyone got this working, I'm having the same issue tried removed node and running node install did not work
