### ISSUE TITLE
`radio_button` id attribute is not generated correctly 

### ISSUE THREAD

**Issue by GBH** [phoenixframework/phoenix_html#194]
See: https://github.com/phoenixframework/phoenix_html/blob/v2.10.5/lib/phoenix_html/form.ex#L668

So if radio button value is "purple elephant", id generated will become `record_field_purple elephant`

I think value needs to be stripped of all spaces before concatenating with `input_id/2` .. or replaced with "_"

**Comment by josevalim** [comment]
Agreed. pr please?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by GBH** [comment]
Will do
