### ISSUE TITLE
Consider adding "external" option to link and form generators

### ISSUE THREAD

**Issue by GriffinMB** [phoenixframework/phoenix_html#196]
Currently, if a developer provides link and form generators an external URL, the `csrf_token` option defaults to true which may result in CSRF tokens leaking to third-party applications.  It could be useful to implement an API similar to the `redirect` function for link/form generators that accepts a `to` and `external` option. If the `external` option is used, `csrf_token` would default to false, but if the `to` option is used the path would be validated.

There are some potential concerns:

* If a dev does this: `link("delete", to: @input, method: :delete)`, I think the change would be fairly natural. However, if they are using forms (`form_for @changeset, @input, fn f ->`), an update would be more difficult. IE how would we want to handle to/external options in forms? Would we want to?
* With path and URL generators, would we want to then validate that `to` is either a path or the current host? Or do we want all full URLs to be `external`?
* Plenty more, I'm sure :)

Would love to hear thoughts, as well as implementation considerations if this sounds like a good idea! And, of course, I'm happy to work on the PR.

**Comment by GriffinMB** [comment]
So, the CSRF token would become something like `myhost.com#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==`? Then, the link/form generators would only set a default token if the hostname validates? 

That definitely sounds like it would be much simpler to implement on the generator side of things.

**Comment by josevalim** [comment]
@GriffinMB I was rather thinking we could sign the host in the token and match that when the request arrives. So a form that points to "www.example.com" would have the host signed in the CSRF token. When the request arrives, we would compare the host in the token with the host in the request. It should work completely transparent for the user.

**Comment by GriffinMB** [comment]
@josevalim Ah. I think I see what you mean now. So, if a form points to "www.example.com" then "www.example.com" is signed in the CSRF token, but if it points to "evil.com" then "evil.com" is signed in the token? Then, when Phoenix is validating the token, it can verify the the Host header matches the CSRF host? I think that should work.

My first thought against it is that an attacker with the ability to overwrite the Host header could circumvent the protection. This would be a browser bug, but it's happened before. Also, a man-in-the-middle attacker with the ability to write arbitrary headers, but (for some reason) not otherwise read request data could bypass this as well. I can't think of a situation where this is likely to occur...

Anyway, since this is more of a defense in depth concern, maybe these "risks" don't matter as much. I'll think more about it, and see if I can think of a concrete reason not to go that route. But it sounds like that could be a solid approach.

**Comment by josevalim** [comment]
If you have other suggestions I would love to hear them. It would be perfect if we could solve this without pushing the complexity to library users.

**Comment by GriffinMB** [comment]
Absolutely! Right now, I think your idea of a signed host in the CSRF token is great. It seems about as close as you can get to non-complex for library users while covering all the edge cases. Just trying to think through any potential security implications :)

**Comment by GriffinMB** [comment]
@josevalim - I do think a signed host is going to be the best option. It's a good idea, and I can't think of any serious/real issues. I suppose this update would require coordinated updates between Plug and Phoenix HTML, but I can work on a PR?

**Comment by josevalim** [comment]
Yeah, the bulk of it is in Plug, so we can start there. A PR is definitely
welcome. I am thinking we will add a get_csrf_token_for function.

We will also need a signing key, we can probably use the one from
Plug.Session.
