### ISSUE TITLE
String keys in phoenix_html forms

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_html#197]
I'm working on a system, which allows users to build custom forms from building blocks we provide. Now as fields are user defined I'd really like to use string names for those fields and not atoms, but it seems phoenix_html does currently expect atom names for form-fields in various places. 

What's the reasoning for requiring atom keys, when they're converted to strings anyways?

**Comment by josevalim** [comment]
Because we only used atoms so far. ;)

A PR that relax this condition and adds some tests is welcome!
