### ISSUE TITLE
Publish phoenix_html on NPM

### ISSUE THREAD

**Issue by seantanly** [phoenixframework/phoenix_html#200]
Can we have `phoenix_html` published on NPM, similar to what is done for `phoenix`?

https://www.npmjs.com/package/phoenix

With that, it allows both `phoenix` and `phoenix_html` to be pulled from NPM registry instead of local path coded dependencies inside `package.json`.

```
    "phoenix": "file:../../../deps/phoenix",
    "phoenix_html": "file:../../../deps/phoenix_html"
```

My aim is to speed up Docker builds. Because dependencies most often do not change as frequently as code, making Docker cache entire dependencies folders such `node_modules` and `deps` enables a much faster build. 

As `phoenix_html` is a local path dependency that further relies on hex package, that makes it not possible for `node_modules` folder to be built/cached solely based on `package.json` and `package-lock.json`, independent from hex packages.

**Comment by josevalim** [comment]
Done! https://www.npmjs.com/package/phoenix_html
