### ISSUE TITLE
input_id() (and thus radio_button()) does not accept an integer value

### ISSUE THREAD

**Issue by jamesvl** [phoenixframework/phoenix_html#204]
## Overview

In version 2.10.5, I could send names and values to `radio_button/3` that were strings and integers, respectively.

In 2.11, this breaks and causes an error.

## Steps to Reproduce

```
$ iex -S mix
iex(3)> alias Phoenix.HTML.Form
Phoenix.HTML.Form
iex(4)> Form.radio_button(:my_form, "my-radio", "1")
# above works in both 2.10.5 and 2.11

# below works in 2.10.5 and fails in 2.11
iex(5)> Form.radio_button(:my_form, "my-radio", 1)
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_id/3

    The following arguments were given to Phoenix.HTML.Form.input_id/3:

        # 1
        :my_form

        # 2
        "my-radio"

        # 3
        1

    Attempted function clauses (showing 2 out of 2):

        def input_id(name, field, value) when is_atom(value)
        def input_id(name, field, value) when is_binary(value)

    (phoenix_html) lib/phoenix_html/form.ex:380: Phoenix.HTML.Form.input_id/3
    (phoenix_html) lib/phoenix_html/form.ex:808: Phoenix.HTML.Form.radio_button/4
```

I believe [this PR](https://github.com/GBH/phoenix_html/commit/bdf7a39296a6388d2ce36ceb082892e65724f79d) introduced the breaking change, when fixing issue #194

I'll submit a PR for a possible fix shortly.

**Comment by jamesvl** [comment]
Pushed a PR, assuming that this bug is legitimate and we want radio buttons to accept integer values. Let me know if you'd like to see anything else in the PR.

**Comment by josevalim** [comment]
I think you forgot to send the PR? :)

Anyway, I think a more complete solution would be use the html safe protocol, so I pushed that instead and kept your tests. Would you please give master a try? If it works I will publish a new release. Thanks!

**Comment by jamesvl** [comment]
Confirmed that master works for my code and radio buttons are once again accepting integer values.

Thank you!

**Comment by josevalim** [comment]
Released!
