### ISSUE TITLE
Feature proposal: data-prompt

### ISSUE THREAD

**Issue by begedin** [phoenixframework/phoenix_html#206]
I like the general approach for the `data-confirm` functionality. Using that as an example, I managed to implement my own version of a `data-prompt` where the behavior is basically

- attributes `data-prompt-message` and `data-prompt-value`
- when the link is clicked, `window.prompt` is called and the user needs to type in the exact value in `data-prompt-value`. If the prompt is dismissed or another value is entered
- both `data-prompt-message` and `data-prompt-value` need to be present for the prompt to trigger

Unfortunately, due to phoenix_html.js enhancing all links generally, I also have to call `stopImmediatePropagation` in my code and basically repeat the entirety of the form creation logic

It works for my specific case, but it got me thinking, would a `window.prompt` be a welcome feature for this library. If so, I could submit a PR first chance I get.

**Comment by josevalim** [comment]
@begedin I would prefer to find a way to make the functionality we have right now easier to compose and/or reuse then adding more feature to the javascript.

**Comment by begedin** [comment]
@josevalim Understandable. Is there any documentation or discussion I could take a look at to understand better what you had in mind? My guess would be a sort of rewrite to separate the `data-confirm` feature from the general link enhancement feature?

**Comment by josevalim** [comment]
@begedin I have no idea as JS is not my strong suite but some sort of callback that would allow you to hook into the form (or similar).

**Comment by begedin** [comment]
If it's acceptable, I can try to work something up (not immediately, need to find the time for it first) and submit a PR as a proposal. At the very least, it can be a starting point for a discussion.

I'm thinking this can probably be closed then.

**Comment by josevalim** [comment]
Beautiful, thank you! :heart:
