### ISSUE TITLE
Why link helper is replacing the href value to "#" for methods other than GET?

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix_html#207]
Hi,

when using the `link` helper with a method other than GET, the `href` attribute of the generated `<a>` tag is set to `"#"`, this can be seen there: https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/link.ex#L106

I know this is purely cosmetic but I like to see the full destination address in the browser status bar when hovering on a link. I think this is also the behaviour when generating links with the Rails framework.

Is there a specific reason not to simply always let the full URL in the `href` attribute?

**Comment by josevalim** [comment]
Sounds good to me. PR please?

**Comment by hlhr** [comment]
A few days ago I thought the same, I will send a PR.

**Comment by wojtekmach** [comment]
Fixed by #209.
