### ISSUE TITLE
problem with date_select

### ISSUE THREAD

**Issue by happysalada** [phoenixframework/phoenix_html#211]
I have a cryptic bug with the dateselect function
I am using phoenix_html "2.11.2"
Here is the code that is problematic
```
<%=
  form_for @conn,
  "/regulated_entity/accounts/new",
  [
    {:"data-controller", "regulated-entity-account-logged-in-form"},
    {:"data-target", "regulated-entity-account-logged-in-form.form"}
  ],
fn form -> %>
  <%= date_select form, :birthday, builder: fn b -> %>
     b.(:day, prompt: "", class: "custom-select") /
     b.(:month, prompt: "", class: "custom-select") /
     b.(:year, options: Timex.now.year..(Timex.now.year - 100), prompt: "", class: "custom-select")
  <% end %>
<% end %>
```
that code will generate an argument error in the datetime_builder function on form.ex
on line 1373 `id = Keyword.get(parent, :id, input_id(form, field))`
the id of my form is nil and that in turns makes the id of my form fields nil and that datetime_builder function doesn't like it.

I don't know how to set the id of a form. When I inspect my form object its id is nil.

Let me know if you need more informations

**Comment by josevalim** [comment]
@happysalada can you please try to add a failing test case to our suite? Thank you.

**Comment by happysalada** [comment]
sure, I'll have a look at it this weekend.

**Comment by happysalada** [comment]
@josevalim I added this https://github.com/phoenixframework/phoenix_html/pull/213
There might be a problem with my usage of the date_select builder function.

**Comment by josevalim** [comment]
You are using `/` which is going to try to compute the division between the return of the builder. You need to remember this is Elixir code and not markup. There are a couple ways you can solve this. For example:

```
  <%= date_select form, :birthday, builder: fn b -> %>
     <%= b.(:day, prompt: "", class: "custom-select") %> /
     <%= b.(:month, prompt: "", class: "custom-select") %> /
     <%= b.(:year, options: Timex.now.year..(Timex.now.year - 100), prompt: "", class: "custom-select") %>
  <% end %>
```

Or by returning a list of expressions:

```
  <%= date_select form, :birthday, builder: fn b ->
     [b.(:day, prompt: "", class: "custom-select"), ?/,
      b.(:month, prompt: "", class: "custom-select"), ?/,
      b.(:year, options: Timex.now.year..(Timex.now.year - 100), prompt: "", class: "custom-select")]
    end %>
```

**Comment by happysalada** [comment]
Thanks!
