### ISSUE TITLE
date_select ignores class option

### ISSUE THREAD

**Issue by troelsim** [phoenixframework/phoenix_html#212]
A `date_select` from an auto-generated form looks like this:
``` 
  <div class="form-group">
    <%= label f, :delivery_date, class: "control-label" %>
    <%= date_select f, :delivery_date, class: "form-control" %>
    <%= error_tag f, :delivery_date %>
  </div>
```
The rendered select elements do not have the "form-control" class, causing styling issues. This is because the `opts` passed to `date_select` don't get passed down to the individual `select`s. I believe that at least `class` should, and that should be in in `datetime_options/7`.

**Comment by troelsim** [comment]
After opening this issue I just realised that the individual `select`s can be customised by passing a `builder` option, and this would probably be the best way to set the class on each select (as `form-control` doesn't exactly look right anyway).

What's confusing, though, is that the `class: "form-control"` from the generated code has no effect.

**Comment by josevalim** [comment]
Yes! @troelsim phoenix master already does not generate the class, so the confusion should be removed. :) thanks for the report!
