### ISSUE TITLE
Would it be possible to add a function to support array type from Ecto?

### ISSUE THREAD

**Issue by x-ji** [phoenixframework/phoenix_html#214]
`Ecto.Schema` provides the `array` type. However, currently it's not straightforward to generate form input for such a type. Manual conversion might be needed between the raw form input and the array type. Somebody came up with [a few functions](https://medium.com/@chipdean/phoenix-array-input-field-implementation-7ec0fe0949d) that generate inputs. Would it be possible to have such a function in the official Phoenix.HTML module, or would it be impractical since the length of array is dynamic and thus will likely involve JavaScript?

**Comment by josevalim** [comment]
Arrays are tricky because they could be handled in many different ways. In some cases, a select is enough. But in other cases, you may want something more dynamic. In such cases, using external functions is fine. Our focus here is to mostly wrap around what HTML provides out of the box.
