### ISSUE TITLE
raw(nil) breaks the contract

### ISSUE THREAD

**Issue by RaymondLoranger** [phoenixframework/phoenix_html#217]
The call 'Elixir.Phoenix.HTML':raw('nil') breaks the contract (iodata() | safe()) -> safe()

To make dialyzer happy, you need to specift raw([]).

**Comment by josevalim** [comment]
Can you please send a PR? Thank you!

**Comment by soteras** [comment]
Why that break the contract?

**Comment by RaymondLoranger** [comment]
Hi,

 

defmodule GallowsWeb.HangmanView.GameStateHelper do

 import Phoenix.HTML, only: [raw: 1]

 

  alias Phoenix.HTML

 

  @spec game_state(atom) :: HTML.safe()

  def game_state(game_state)

  def game_state(:won), do: alert(success: "You Won!")

  def game_state(:lost), do: alert(danger: "You Lost!")

  def game_state(:good_guess), do: alert(success: "Good guess!")

  def game_state(:bad_guess), do: alert(warning: "Bad guess!")

  def game_state(:already_used), do: alert(info: "You already guessed that")

  def game_state(_), do: raw([])

 

  ## Private functions

 

  @spec alert(Keyword.t()) :: HTML.safe()

  defp alert([{class, message}]) do

    """

    <div class="alert alert-#{class}">

      #{message}

    </div>

    """

    |> raw()

  end

end

 

 

If you specify raw(nil) above instead of raw([]), Dialyzer will complain about breaking the contract.

 

In the Phoenix documentation, they do mention raw(nil) however:

 

https://hexdocs.pm/phoenix_html/Phoenix.HTML.html#raw/1

 

raw(value) View Source

raw(iodata() | safe()) :: safe()

Marks the given content as raw.

 

This means any HTML code inside the given string won’t be escaped.

 

iex> raw("<hello>")

{:safe, "<hello>"}

iex> raw({:safe, "<hello>"})

{:safe, "<hello>"}

iex> raw(nil)

{:safe, ""}
