### ISSUE TITLE
Delete link / method does not work, its not generating the form wrapper 

### ISSUE THREAD

**Issue by AlmogRnD** [phoenixframework/phoenix_html#218]
I have the following in my app 

`<%= link to: magnet_path(@conn, :delete, magnet), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-icon-toggle btn-refresh" do %>`

Which does not but add # at the end of the URL in my browser. 

This is the output code in the browser which is correct 

```
<a class="btn btn-icon-toggle btn-refresh" data-confirm="Are you sure?" data-csrf="UTYOO0sSHwcLVjkzNUgHAigNZD0IJgAA5xwS/ZlUg0uKZ2diBYOsOQ==" data-method="delete" data-to="/magnets/27" href="#" rel="nofollow">
                                                <span class="md md-delete"></span>
</a> 
```

When I look at the entire element there is no form wrapper that is being generated, which is why the data method is not working 

Entire HTML output 

<img width="1044" alt="screen shot 2018-05-27 at 12 01 08 am" src="https://user-images.githubusercontent.com/169507/40576920-1c50d5cc-6141-11e8-9f22-d2f7c1c1a6e3.png">

**Comment by AlmogRnD** [comment]
I just ran mix deps.update --all and to make sure I have the latest version (was it published to hex) I', still getting the #

Here is a gif 
![bug](https://user-images.githubusercontent.com/169507/40577188-c5d85ab8-6144-11e8-902a-d76c6b8a4611.gif)

**Comment by AlmogRnD** [comment]
@josevalim would you like access to my app?

**Comment by josevalim** [comment]
@AlmogRnD we do not have time to investigate each application individually. That's why we ask for a minimal test case.

Also, make sure that the phoenix_html.js is being included in your output javascript code. By default Phoenix includes it but it may not be the case if you changed how Phoenix compiles your assets.

Finally, the commit that no longer adds `#` is only on master, it has not been published yet: https://github.com/phoenixframework/phoenix_html/commit/09acd6417a9e2818d56b209a996406119804f4f4

**Comment by AlmogRnD** [comment]
It is as I'm getting the following error in my console 

<img width="1380" alt="screen shot 2018-05-27 at 12 56 56 am" src="https://user-images.githubusercontent.com/169507/40577443-f5ca08b2-6148-11e8-9222-a12d41abfd05.png">

<img width="1358" alt="screen shot 2018-05-27 at 12 57 01 am" src="https://user-images.githubusercontent.com/169507/40577445-f847340c-6148-11e8-802d-10795285b663.png">

**Comment by AlmogRnD** [comment]
I also created a new app using mix phx.new hello and I don't have this issue?

**Comment by josevalim** [comment]
> I also created a new app using mix phx.new hello and I don't have this issue?

So it is an issue in your app. See how the new app is importing phoenix_html, make sure you are using the same deps and you should be good to go.

**Comment by AlmogRnD** [comment]
I have two different templates so I need to load my assets per template I'm loading app.js which has the phonix html import like so 

`<script src='<%= static_path(@conn, "/js/admin/app.js ") %>'></script>`

and not from brunch, so is doing it like so supported?

**Comment by AlmogRnD** [comment]
Also there seems to be something wired when I look at the source 

New app I just created 

<img width="281" alt="screen shot 2018-05-27 at 1 32 27 am" src="https://user-images.githubusercontent.com/169507/40577783-29c58fba-614e-11e8-9c18-b248e713b8a9.png">

And my app 

<img width="290" alt="screen shot 2018-05-27 at 1 34 04 am" src="https://user-images.githubusercontent.com/169507/40577786-2f84d29e-614e-11e8-9dc7-6944c1037a2d.png">

Any ideas why this is happing?

**Comment by josevalim** [comment]
> and not from brunch, so is doing it like so supported?

It is not that it isn't supported, you just need to configure your build tool to include phoenix_html in both. It is really up to your build tool, there is nothing about Phoenix. :)

**Comment by AlmogRnD** [comment]
@josevalim I created a brand new project and added the basic template and the issue is happing, I also removed all the JS files to make sure this was not causing the issue here is the demo with the issue - https://www.dropbox.com/s/sruvkugvha4uqmq/magnify.zip?dl=0

The only difference  is I have the following in my routing 

```
pipeline :admin_layout do
    plug(:put_layout, {MagnifyWeb.LayoutView, :admin})
  end
```

So I can spilt up public pages like login, registration which a different design than my main dashboard and I have two layout files admin and app

**Comment by AlmogRnD** [comment]
@josevalim not sure I understood I have the following in my brunch config in the join to 

` 'js/app.js': /^(assets\/js\/admin)/,`

But brunch is not loading anything am I missing something?

**Comment by AlmogRnD** [comment]
The issue is something to do with 

03:32:42 - warn: js/app.js compiled, but not written. Check your javascripts.joinTo config 

It's not getting sent to static which is why I can't see it in the browser when I inspect
