### ISSUE TITLE
input_id/3 argument error when used in a form without :as option

### ISSUE THREAD

**Issue by jasmineleonard** [phoenixframework/phoenix_html#222]
At line 388 in `form.ex`, the `input_id/3` function returns:

```elixir 
input_id(name, field) <> "_" <> value_id
```

This raises an ArgumentError when `input_id(name, field)` returns `nil`, because it cannot be concatenated with the rest of the string.  

Despite the fact that the function specification for `input_id/2` says that it should return a string, it will actually return `nil` when the first argument is a `Phoenix.HTML.Form` that has `id: nil` (line 368):

```elixir 
@spec input_id(t | atom, field) :: String.t()
def input_id(%{id: nil}, _field), do: nil
```

And a form's `id` will be `nil` if the form was created without the `:as` option being set.

Since `input_id/3` is called within `radio_button/4`, this error occurs when trying to add a radio button within a form that does not have the `:as` option set.

This could be fixed either by making sure `input_id/2` always returns a string (as per the spec), or by checking `input_id/2`'s return type when it's called within `input_id/3` and handling accordingly.

**Comment by josevalim** [comment]
Thanks @jasmineleonard. I think not having `as: ...` was a requested feature, so we need to make sure we handle the cases where we don't have an `id` and document that input_id may return nil.

**Comment by jasmineleonard** [comment]
Alternatively, when `id` is `nil`, `input_id/2` could just return the name of the field?  ie.

```elixir
def input_id(%{id: nil}, field), do: "#{field}#"
```

**Comment by josevalim** [comment]
@jasmineleonard I like that, we can try it!

**Comment by jasmineleonard** [comment]
Great, thanks! :)

**Comment by josevalim** [comment]
@jasmineleonard would you please send a PR with tests? :) Let me know if you have any questions!

**Comment by jasmineleonard** [comment]
@josevalim Sure thing, PR submitted :)
