### ISSUE TITLE
checkbox's :checked_value option overrides :value option

### ISSUE THREAD

**Issue by ZombieHarvester** [phoenixframework/phoenix_html#231]
## Case 1
```
= checkbox :contract, :online, value: true
```
generates
```
<input id="contract_online" name="contract[online]" value="true" checked="" type="checkbox">
```
checkbox appears checked.

## Case 2
```
= checkbox :contract, :online, value: true, checked_value: false
```
generates
```
<input id="contract_online" name="contract[online]" value="false" type="checkbox">
```
checkbox appears unchecked, though `:value` is still set to `true`

## Question
Is it the intended behaviour? Perhaps it should be mentioned in the docs. It says `:checked_value - the value to be sent when the checkbox is checked`, it doesn't look like it supposed to override `:value` which is `used to check if a checkbox is checked or unchecked` according to docs.

## Current workaround
My current solution is to use `:checked` property instead of `:value`
```
= checkbox :contract, :online, checked: true, checked_value: false
```
generates
```
<input id="contract_online" name="contract[online]" value="false" checked="" type="checkbox">
```
checkbox appears checked and it sends false on submit as expected.

**Comment by josevalim** [comment]
Yes, this is working as intended. The `value` that you pass is compared against `checked_value`, if they are different, then it means it is not checked. :) If this is not clear, improvements to the docs are always appreciated. :)

**Comment by ZombieHarvester** [comment]
thanks @josevalim
