### ISSUE TITLE
Option to disable unchecked_value for checkbox

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_html#232]
Sometimes (e.g. when using a filter form and GET requests) one does not need to send unchecked values, but just what actually has been selected. It would be nice if there would be an option for that in the checkbox function.

**Comment by LostKobrakai** [comment]
Maybe something like `checkbox f, :test, unchecked_input: :skip`. I'm actually not to keen on adding another function, as it's still a checkbox.

**Comment by josevalim** [comment]
Maybe `hidden_input: false`?

**Comment by LostKobrakai** [comment]
Would work for me.

**Comment by josevalim** [comment]
PR please? :)

**Comment by LostKobrakai** [comment]
I'll see what I can do. I'll be currently quite busy then next days and was just leaving this here. Maybe something for hacktoberfest?
