### ISSUE TITLE
Formatting numbers in `number_input`

### ISSUE THREAD

**Issue by mschae** [phoenixframework/phoenix_html#235]
Apologies if this was discussed before, I couldn't find a discussion.

`Phoenix.HTML.number_input/2` displays numbers (at least floats) in scientific notation. We would like to display them in non-scientific notation.

Would you suggest wrapping `number_input` in a custom helper or should the possibility to add a custom format for displaying numbers be part of Phoenix.HTML? If so I'd be glad to suggest a PR.

**Comment by josevalim** [comment]
I think we default to whatever Elixir's `to_string` does but you should be to format as you wish and pass the value as `value: "123.34"`?

**Comment by mschae** [comment]
Absolutely and that's why I wanted to discuss whether we need to change anything at all.

It can be repetitive to write something along the lines of `number_input form, :field, value: form.data.field` when instead we could use something along the lines of `number_input form, :field, formatter: &my_custom_value_formatter/1`. That's how I would end up doing it internally so I wanted to discuss whether my use case is isolated, or if a formatter option (or something comparable) would be a wortwhile addition to phoenix_html.

**Comment by josevalim** [comment]
What if you build a function that instead calls `number_input`? Like `formatted_number_input` or similar?

**Comment by mschae** [comment]
That’s exactly what I would do right now. Just wondering whether this is a common enough problem to warrant a PR. Answer (especially given the option you suggested) might very well be no. :)

**Comment by josevalim** [comment]
> That’s exactly what I would do right now. 

Assuming that it works, then I don't think we need to change phoenix_html. :)

**Comment by mschae** [comment]
That’s fair, I’ll go ahead and close this issue.
