### ISSUE TITLE
`csrf_token_generator` vanished

### ISSUE THREAD

**Issue by OvermindDL1** [phoenixframework/phoenix_html#236]
It appears that in the latest released version v2.12.0 that the `:csrf_token_generator` configuration option has vanished without any mention in the changelog or any backwards incompatibility report where it previously existed on older versions, thus a standard semver upgrade broke an existing installation in a very surprising way.  This option was documented in the guide and was not an internal option.  It appears to have been removed from commit c5843aedc92ade21f6c6a544b7538b90f6e5d257 a while back now.

I've already worked around it, but at the very least this needs to be documented as a backwards incompatibility in the changelog and it really should have been a major version bump and not just a surprising ignoring of a previously set option.

**Comment by josevalim** [comment]
Yup, in this case we totally missed it as a backwards incompatible change, otherwise we would have shipped it as 3.0. Now the best we can do is to add it to the CHANGELOG. :(

**Comment by OvermindDL1** [comment]
> Now the best we can do is to add it to the CHANGELOG. :(

+1

I would also recommend testing for if the `csrf_token_generator` option is set at compile-time and issuing a warning to update to the new Plug CSRF handling so anyone else that might be caught by it like I was will know what happened and what needs to change.  :-)

**Comment by OvermindDL1** [comment]
As well as possible also setting an invalid value as that application option for if it is being read by someone then it will fail the match pretty visibly.  :-)
