### ISSUE TITLE
target.getAttribute not defined in phoenix.link.click event handler

### ISSUE THREAD

**Issue by newtrat** [phoenixframework/phoenix_html#238]
Running `phoenix_html` 2.12, reporting a possible bug.

We've gotten automated bug reports like `Object doesn't support property or method 'getAttribute'` and `e.target.getAttribute is not a function`. These reports come exclusively from desktop/laptop versions of Edge, Chrome, and IE. According to our source map, they're coming from the event handler for `phoenix.link.click`.

```javascript
  window.addEventListener('phoenix.link.click', function (e) {
    var message = e.target.getAttribute("data-confirm"); // <--- THIS LINE
    if(message && !window.confirm(message)) {
      e.preventDefault();
    }
  }, false);
```

I don't understand how that's possible, since the window-wide click listener checks that `getAttribute` exists before dispatching the `phoenix.link.click` event:
```javascript
while (element && element.getAttribute) {
  // ...
  if (!element.dispatchEvent(phoenixLinkEvent)) {
    // ...
  }
  // ...
}
```

Have you seen this issue before? Any idea what could be making the event's target change between when the event gets dispatched and when the handler is run? I haven't yet been able to reproduce the bug myself to examine in more detail.

**Comment by josevalim** [comment]
Just a note that we haven’t seen it before. But hopefully others that have
can now converge here. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Btw, are you using the .js file from npm or directly from the phoenix_html dependency? Maybe the npm version is out of date which could cause the bug? Can you check if the code you are using is the exact same as in this repository?

**Comment by newtrat** [comment]
We're using the version installed by the phoenix_html Elixir dependency (our package.json has `"phoenix_html": "file:../deps/phoenix_html`). The code we're using is the same as this repository's version except for style changes introduced when I accidentally ran my autoformatter on `node_modules` :smile:

Sorry I can't be more helpful -- I wasn't able to reproduce this bug after a few days of trying. Will update here if I get more details in the future.

**Comment by josevalim** [comment]
Thanks, please let us know if you can reproduce it and we will gladly take a look at it!

**Comment by sn3p** [comment]
Same problem here for users on IE11 and Edge. I tried reproducing this but couldn't.

> Object doesn't support property or method 'getAttribute'

```js
// Overriding the default confirm behaviour
document.body.addEventListener("phoenix.link.click", event => {
    event.stopPropagation();

    const message = event.target.getAttribute("data-confirm");

    if (!message) {
      return true;
    }

    // Custom implementation here ...
  },
  false
);
```

(as per [docs](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2-overriding-the-default-confirm-behaviour))

---

I'm a bit confused when `phoenix.link.click` is dispatched. I would expect this to happen only when clicking a link. But for me it fires multiple times for a single click (even when not clicking a link). The event is dispatched for every element traversing up the DOM tree. Is this supposed to happen?
