### ISSUE TITLE
form_for dialyzer errors after update to 2.13

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix_html#239]
Version
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.4 (compiled with Erlang/OTP 21)
phoenix 1.4.0
phoenix-html 2.13.0

Current behavior
The code
```
<%= form_for @changeset, @action, fn f -> %>
...
```
results in following dialyzer error
```
Function 'my_form.html'/1 has no local return
The call 'Elixir.Phoenix.HTML.Form':form_for(any(),any(),fun((_) -> {'safe',[any(),...]})) will never return since it differs in the 3rd argument from the success typing arguments: (any(),any(),maybe_improper_list())
```

Expected behavior
dialyzer should not complain as in earlier versions

**Comment by lukaszsamson** [comment]
Yes, I've seen that. I'll try to make it work.

**Comment by lukaszsamson** [comment]
@josevalim I can verify that passing options explicitly avoids the issue
```
<%= form_for @changeset, @action, [], fn f -> %>
```
I also run dilayzer on master phoenix_html and there are at least 2 issues that seem related.
1. FormData.to_form implementation should set `:action` (or Form typespec should allow nil)
```
The inferred return type of to_form/2 (#{'__struct__':='Elixir.Phoenix.HTML.Form', 'action':='nil', 'data':=#{}, 'errors':=_, 'hidden':=[], 'id':=_, 'impl':='Elixir.Phoenix.HTML.FormData.Plug.Conn', 'index':='nil', 'name':=_, 'options':=[{atom(),_}], 'params':=_, 'source':=atom() | #{'params':=_, _=>_}}) has nothing in common with #{'__struct__':='Elixir.Phoenix.HTML.Form', 'action':=binary(), 'data':=#{atom() | binary()=>_}, 'errors':=[{atom(),_}], 'hidden':=[{atom(),_}], 'id':=binary(), 'impl':=atom(), 'index':='nil' | non_neg_integer(), 'name':=binary(), 'options':=[{atom(),_}], 'params':=#{binary()=>_}, 'source':=_}, which is the expected return type for the callback of the 'Elixir.Phoenix.HTML.FormData' behaviour
```
2. dialyzer is complaining that the new form_for has invalid contract.
```
The contract 'Elixir.Phoenix.HTML.Form':form_for('Elixir.Phoenix.HTML.FormData':t(),'Elixir.String':t(),'Elixir.Keyword':t()) -> 'Elixir.Phoenix.HTML':safe()
    ; ('Elixir.Phoenix.HTML.FormData':t(),'Elixir.String':t(),fun((t()) -> 'Elixir.Phoenix.HTML':unsafe())) -> 'Elixir.Phoenix.HTML':safe() cannot be right because the inferred return for form_for(_form_data@1::any(),_action@1::any(),[]) on line 303 is #{'action':=_, _=>_}
The contract 'Elixir.Phoenix.HTML.Form':form_for('Elixir.Phoenix.HTML.FormData':t(),'Elixir.String':t(),'Elixir.Keyword':t()) -> 'Elixir.Phoenix.HTML':safe()
    ; ('Elixir.Phoenix.HTML.FormData':t(),'Elixir.String':t(),fun((t()) -> 'Elixir.Phoenix.HTML':unsafe())) -> 'Elixir.Phoenix.HTML':safe() cannot be right because the inferred return for form_for(_form_data@1::any(),_action@1::any(),_options@1::any()) on line 376 is #{'action':=_, _=>_}
```

**Comment by Will-W** [comment]
I'm sure you're aware as this is still open, but just in case there was any doubt, I am still seeing this with *some* of my calls to `form_for` in 2.13.1. Can't see any rhyme or reason to why some are ok and others aren't, but I'm not that familiar with the dialyzer yet.

In all cases, the warning was silenced by explicitly providing the options argument.

**Comment by OvermindDL1** [comment]
Hitting this same dialyzer error.  I'm guessing the `when is_function(fun, 1)` guard is overriding it or something, or perhaps the specs not all being on the main head perhaps?  Dialyzer is reporting that the *only* success typing is `form_for(any(),any(),maybe_improper_list())` so perhaps the later specs are just being ignored because the function is defined at that point?  I'm also curious why the first two arguments are `any()`'s instead of the referenced types...
