### ISSUE TITLE
The use of `search_path` can be really confusing.

### ISSUE THREAD

**Issue by RichMorin** [phoenixframework/phoenix_html#248]
In the "With connection data" section of `phoenix_html/lib/phoenix_html/form.ex`, the name `search_path` is used in the example.  I found this quite confusing, because I took it to be a fixed function name, rather than one generated from the controller name, etc.  Making matters worse, the controller I was using as a starting point was named `SearchController`, so it worked but my attempts to use a `search_path` call with my `ItemController` did not.

Please consider using metasyntactic naming as a way to clarify things. For example, use the function name `foo_path` and mention that the corresponding controller would be named `FooController`.

**Comment by josevalim** [comment]
Can you please send a pull request? Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by RichMorin** [comment]
Sure. See "attempt to clarify the example #249" as a first cut at clarifying the example.
