### ISSUE TITLE
Bug: Nonce not allowed on script tags?

### ISSUE THREAD

**Issue by tomciopp** [phoenixframework/phoenix_html#254]
So this is a weird issue, I'm trying to modify my inline script tags to add nonces to comply with a stricter CSP but I'm running into a weird issue where the value is stripped before rendered to the page.

If I add the following code in a template ` <script type="text/javascript" nonce="1234">` It renders 

```javascript
<script type="text/javascript" nonce>
```

If I change the attribute name from 'nonce' to 'foo'  it renders

```javascript
<script type="text/javascript" foo="1234">
```

This is surprising because the application is not behaving how I am telling it to, and it is not obvious why the value is being stripped. I'm unsure if this is a bug or feature and if it is a feature how can it be overridden.

**Comment by josevalim** [comment]
We don’t change this in anyway. My suggestion is for you to curl the URL
and see if the nonce is there. If it is, it is the browser removing it for
some reason, probably unrelated to Phoenix.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tomciopp** [comment]
It looks like it is the browser removing it.
