### ISSUE TITLE
`inputs_for` option to not automatically generate the id field

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_html#258]
Currently a structure like the following is not possible using `inputs_for` because the hidden id input is always added as sibling to the user defined markup. Maybe the markup for the id input could optionally be supplied to the callback, so the user can place it somewhere.

```eex
<ol>
  <%= inputs_for f, :fields, fn finner -> %>
    <li>[…]</li>
  <% end %>
</ol>
```

```html
<ol>
  <input type="hidden" …>
  <li>[…]</li>

  <input type="hidden" …>
  <li>[…]</li>

  <input type="hidden" …>
  <li>[…]</li>
</ol>
```

**Comment by josevalim** [comment]
A PR to add an option that skips the id field (so you add it manually) is welcome!
