### ISSUE TITLE
Form name

### ISSUE THREAD

**Issue by nenros** [phoenixframework/phoenix_html#26]
Hi!
I tried to create form for angularjs using form_for. Agnualrjs use name attribute of form tag, but using form_for function is impossible to write this attribute, because name is used for input names. Maybe it should also add name attribute to form tag?

**Comment by josevalim** [comment]
That sounds reasonable, yes. Can you please send a pull request? :)

@chrismccord do you agree here?

**Comment by chrismccord** [comment]
Yes, but what will we name the option given that name is overloaded?

**Comment by josevalim** [comment]
It is the same. We will just write it down as a form attribute too.

**Comment by josevalim** [comment]
Actually, I don't like coupling these two. I think we should go with `:as` for configuring the underlying name and leave `:name` be.

**Comment by josevalim** [comment]
Here is a possible solution to the problem: 9e0a36befb0923a36f65e3f164d63283775e96d8

Thoughts? Does it work for you @nenros? If everyone agrees, 2.2.0 will be released.

**Comment by nenros** [comment]
for me it is ok! :+1:
