### ISSUE TITLE
Code coverage missing when functions called inside ~E

### ISSUE THREAD

**Issue by TheFirstAvenger** [phoenixframework/phoenix_html#260]
[This minimal reproduction repository](https://github.com/TheFirstAvenger/sigil_e_coverage_test) demonstrates an issue we ran into whereby lines inside a `~E` are being incorrectly reported as not covered in test coverage.
In short, a test covered view function like this one:
```elixir
  def foo do
    IO.puts("this is covered")

    ~E"""
    call to bar is not
    <%= bar() %>
    """
  end
```
will report green for:
```elixir
    IO.puts("this is covered")
```
but red for
```elixir
    <%= bar() %>
```

**Comment by josevalim** [comment]
Thanks for the minimal case, it makes fixing it much easier. ❤️ :
