### ISSUE TITLE
inputs_for/4 with prepend/append and field is present

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix_html#267]
https://github.com/phoenixframework/phoenix_html/blob/b4bdff5599ac03ad4d72f112fffb189f14f4a970/test/phoenix_html/inputs_for_test.exs#L179-L187

Is this test correct? It seems to indicate that `append` and `prepend` are ignored if there are any values. If that's what's supposed to happen, how are those options different from `default:` ?

**Comment by josevalim** [comment]
The test is poorly written. We don't add them when *parameters* are sent. We do add them if the field exists.

**Comment by benwilson512** [comment]
Gotcha, and a parameter is something that is passed in via `cast / change / etc/`?

**Comment by josevalim** [comment]
Yes!
