### ISSUE TITLE
link/2 throws "unsupported scheme" exception when uppercase characters are in the URL scheme.

### ISSUE THREAD

**Issue by SylvainBigonneau** [phoenixframework/phoenix_html#272]
phoenix_html version: v2.13.3
elixir version: 1.8.2
erlang version: 21.3.7

I have a slight discrepancy error in my Phoenix app, where `URI.parse` will accept uppercase letters in my URL scheme ("Http://google.com" for example) but when using this same URL in `Phoenix.HTML.Link.link/2`, I get this exception:

> unsupported scheme given to link/2. In case you want to link to an unknown or unsafe scheme, such as javascript, use a tuple: {:javascript, rest}

From what I have read here and there, only lowercase characters should be allowed in URL schemes, but uppercase characters are tolerated.

Any idea how to deal with this issue idealy?

**Comment by josevalim** [comment]
URI.parse only parses URLs, but does not validate them. So maybe you can further validate the URLs after parsing them? But do note that uppercase schemes is actually valid. The only reason why we limit `link/2` is because linking to external sites can be a security issue, so we keep the validation as barebones as possible.

**Comment by SylvainBigonneau** [comment]
Thanks! That's clarifying enough.

As you said, these uppercase schemes are valid, so I am not sure about restricting them, I would rather be able to display links based on these uppercase schemes nonetheless. Should I just... lowercase my urls before passing them to `link/2` then?

**Comment by josevalim** [comment]
@SylvainBigonneau downcasing the whole URL would be in incorrect but you can safely downcase the scheme.

**Comment by SylvainBigonneau** [comment]
Alright, thanks for the advice!

**Comment by shijithkjayan** [comment]
@josevalim what do you mean by `safely downcase the scheme` ? I too am facing the issue reported by @SylvainBigonneau , so if you can please explain how to downcase the scheme, it would be very helpful

**Comment by josevalim** [comment]
@shijithkjayan after you parse the URL with URL.parse, you can do `update_in url.scheme, &String.downcase/1`.

**Comment by shijithkjayan** [comment]
ok, thanks @josevalim

**Comment by shijithkjayan** [comment]
I just noted that on calling `URI.parse` on a url, the parse function automatically downcases the scheme.

`iex(1)> URI.parse("Http://example.com")
%URI{
  authority: "example.com",
  fragment: nil,
  host: "example.com",
  path: nil,
  port: 80,
  query: nil,
  scheme: "http",
  userinfo: nil
}
`

So we don't have to downcase it again, right? @josevalim

**Comment by josevalim** [comment]
Oh, even better!

**Comment by SylvainBigonneau** [comment]
For reference, here is what I ended up going with:

`<%= link(gettext("Link text"), to: URI.parse(page_url) |> URI.to_string %>`

I am still finding it a little inconvenient to go through all this fluff just for a capitalized scheme in my URL string, but I couldn't find any shorter.

**Comment by shijithkjayan** [comment]
To avoid that congestion I moved `URI.parse(page_url) |> URI.to_string` to my view module.

`<%= link("Click here", to: normalize_link(url) %>`

**Comment by josevalim** [comment]
And ideally, if the link is coming from  the database or something, you want to normalize it before storing it in the DB. :)
