### ISSUE TITLE
data-disable-with

### ISSUE THREAD

**Issue by augnustin** [phoenixframework/phoenix_html#275]
Is there any plan of increasing phoenix_html.js features, inspired from rails_ujs?

Eg. `data-disable-with="Sending ..."` to prevent multiple button clicks/submits.

It would simply look like:

```
window.addEventListener('phoenix.link.click', function (e) {
    var content = e.target.getAttribute("data-disable-with");
    if(content) {
      $(e.target).text(content);
    }
    setTimeout(() => {
      $button.disabled = true;
    }, 0);
  }, false);
```

I also miss `data-remote` a lot but that's would be for another issue...

**Comment by josevalim** [comment]
There are no such plans! But you can always drop those JS scripts yourself. :) thanks for asking!

**Comment by augnustin** [comment]
Thanks for getting back.

Could you elaborate on this answer? Has this already been discussed? I reckon this should be documented then since I guess I'm not the only one coming from Rails' world, expecting to find the same fullstack APIs. 

IMHO this is 100% independent from the phoenix platform, super easy to plug/unplug, hence could come at no cost.

**Comment by josevalim** [comment]
I don't think we should document things we don't do, even if based on users expectations. Should we also document what Django or Express does not do for users coming from said background? None of our forms and links functions document these options, so it is expected that they won't be supported.

> IMHO this is 100% independent from the phoenix platform, super easy to plug/unplug, hence could come at no cost.

And this is exactly why it doesn't have to be part of Phoenix. :)

**Comment by OvermindDL1** [comment]
> And this is exactly why it doesn't have to be part of Phoenix. :)

Same reason I don't see why the other javascipt helpers exist for like a delete popup and so forth, perhaps those should be removed?

**Comment by josevalim** [comment]
Maybe they shouldn't haven't been added but there is no way we can remove them without breaking tons of applications. :/

**Comment by OvermindDL1** [comment]
What about migrating them to a new javascript library that can hold a variety of helpers like that (or to an existing javascript library that contains those same features and more) and just deprecate the existing built-in one?

**Comment by augnustin** [comment]
We should definitely start an other repo from scratch.

**Comment by josevalim** [comment]
Yeah, please do. We don’t plan to maintain as part of Phoenix but it sounds
like a good idea for a community package.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
