### ISSUE TITLE
Phoenix.HTML.Form.input_type gives me the same field for an integer as a float

### ISSUE THREAD

**Issue by johannesE** [phoenixframework/phoenix_html#279]
I have created an input helper, which looks like this:

```
  def input(form, field) do
    type = Phoenix.HTML.Form.input_type(form, field)  # <-- See this line

    wrapper_opts = [class: "field"]
    label_opts = [class: "label"]
    input_opts = [class: "input #{state_class(form, field)}"]

    content_tag :div, wrapper_opts do
      label = label(form, field, Gettext.dgettext(DatabaumWeb.Gettext, "form", humanize(field)), label_opts)
      input = apply(Phoenix.HTML.Form, type, [form, field, input_opts])
      error = content_tag :p, class: "help is-danger" do
        ErrorHelpers.error_tag(form, field)
      end
      [label, input, error || ""]
    end
  end
```

Schema:
```
  schema "devices" do
    # more fields
    field :cal_vwc, :integer, default: 0
    field :cal_ec, :integer, default: 0
    field :cal_temp, :float, default: 0.0
    field :cal_air_temp, :float, default: 0.0
  end
```

The problem is, that this gives me an input which has `type="number"`. My browser does not allow me to input decimal values like `1.2` in there.

I can use something like `step="0.1"` in combination with the number input, but I have no idea how to find out that the field contains a float. Otherwise I'd prefer that `Phoenix.HTML.Form.input_type(form, field)` would give me a text input for a float. 

The function also contains a comment `# TODO: Remove me on 3.0`, which makes me doubt my general approach. https://github.com/phoenixframework/phoenix_html/blob/v2.13.3/lib/phoenix_html/form.ex#L539

**Comment by josevalim** [comment]
Good call. Please send a PR that makes the fields :text for floats. Thanks!
