### ISSUE TITLE
form_for function creates a _method attribute with put value for new objects

### ISSUE THREAD

**Issue by JustMikey** [phoenixframework/phoenix_html#28]
How to reproduce the problem:

1) Pull https://github.com/JustMikey/phoenix-test-app

2) install deps and migrate

3) Go to /registration path and create any record

4) Open /registration again

5) Try to create another record with the same username

6) It will render the form again saying that the username is already taken and add a `_method` attribute with value equal to `put`

7) Try to submit the form again, it will tell you that there is no path for "PUT /registration"

**Comment by josevalim** [comment]
Can you please give Ecto master a try and let us know how it goes? Thank you!

**Comment by JustMikey** [comment]
it works fine, you can close this. Sorry for the bother.

**Comment by josevalim** [comment]
@JustMikey it was not a bother. I was not clear but I have just fixed it in master due to your report! Thanks! :D Ecto 1.0.2 should come today or tomorrow!
