### ISSUE TITLE
content_tag/3 doesn't accept a string argument

### ISSUE THREAD

**Issue by rockwood** [phoenixframework/phoenix_html#281]
I'm using the `tag` and `content_tag` functions to generate custom web component elements. Per the spec, custom elements must have dashed names like:

    <my-component></my-component>

The `tag/2` function currently allows a string argument

    iex> safe_to_string tag("my-component")
    "<my-component>"

However, the `content_tag/3` function does not:

    iex> safe_to_string content_tag("my-component", "content")
    ** (FunctionClauseError) no function clause matching in Phoenix.HTML.Tag.content_tag/2

Would it be possible to allow a string argument to the `content_tag` function? 

Another alternative would be to require atoms, but replace underscores with dashes:

    iex> safe_to_string content_tag(:my_component, "content")
    "<my-component>content</my-component>"

That would match the behavior that currently exists for `data` attributes:

    iex> safe_to_string tag(:div, data: [my_attr: "foo"])
    <div data-my-attr="foo">

**Comment by josevalim** [comment]
Hi, please do send a PR so we support strings on content_tag too!

**Comment by OvermindDL1** [comment]
I think supporting strings would be useful, but you can use `:"my-content"` atom as well.
