### ISSUE TITLE
Hacking `Phoenix.HTML.Engine` to provide basic minification

### ISSUE THREAD

**Issue by alizain** [phoenixframework/phoenix_html#287]
How do y'all feel about adding basic minification to the HTML that `phoenix_html` produces? (behind an optional flag, ofcourse)

Essentially, we'd remove newline and tabstop characters during compilation in [`iodata`](https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/engine.ex#L52):

```elixir
defmodule Phoenix.HTML.Engine do
  # other stuff...

  @impl true
  def handle_text(state, text) do
    text =
      text
      |> String.replace("\n", "")
      |> String.replace("\t", "")

    %{iodata: iodata} = state
    %{state | iodata: [text | iodata]}
  end

  # other stuff...
end
```

This approach has been tested on some of my projects. The alternative is to minify the result of every single request - this approach is much more robust minification but also costly and difficult to implement in all environments.

The reasoning for adding minification is that HTML can be whitespace sensitive (especially for inline elements), and I don't want to write minified HTML in source files.

**Comment by josevalim** [comment]
We don’t plan to implement this ourselves but you can have your own engine that wraps our engine callbacks to provide it. Thanks!

**Comment by alizain** [comment]
Thanks @josevalim 👍
