### ISSUE TITLE
12.14.0 tag missing

### ISSUE THREAD

**Issue by PragTob** [phoenixframework/phoenix_html#289]
:wave: Hello lovely people,

first and foremost thank you for your excellent work! :green_heart: 

Secondly, the tag for 2.14.0 is missing here (maybe someone forgot `git push --tags` ?) and hence the code links in the docs lead to my favorite 404 page: https://github.com/phoenixframework/phoenix_html/blob/v2.14.0/lib/phoenix_html/form.ex#L694

Workaround: use docs for older version :)

Thanks and have a wonderful day :wave:

**Comment by josevalim** [comment]
Pushed, thank you and have a great day too!

**Comment by PragTob** [comment]
As always, the fastest maintainer :eyes: :rocket: :unicorn:
