### ISSUE TITLE
Possibility to use live_component inside of inputs_for

### ISSUE THREAD

**Issue by feliperenan** [phoenixframework/phoenix_html#291]
If we try to use a [live_component](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#content) from Phoenix Live View inside of `inputs_for`, we are going to receive an error like this:

```
** (ArgumentError) cannot convert component SomeComponent to HTML.
```

As far as I understood, it's one of [live_component limitations](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-limitations). 

I think we could introduce a similar function like `form_for/3` to `inputs_for` so that this function will not take a function as argument allowing us to render `live_component` inside of it. Something like this:

```EEX
<%= for i <- inputs_for(f, :children) do %>
  // TODO: need to figure out how to generate hidden ids autommatically.
  <div class="field">
    <%= input i, :name %>
  </div>

  <div class="field">
    <%= live_component @socket, SomeComponent, id: :id, form: i %>
  </div>
<% end %>
```

Does it make sense @josevalim? I have similar version working on an App that I've been working and I'm wondering if it would make sense to have it here as well :thinking: .

**Comment by josevalim** [comment]
Yes, it makes total sense. Please send a PR to add such function!
