### ISSUE TITLE
csrf_meta_tag generates invalid HTML

### ISSUE THREAD

**Issue by jaimeiniesta** [phoenixframework/phoenix_html#294]
The tag produced by `csrf_meta_tag()`  produces something like this:

```html
<meta charset="UTF-8" content="12345" csrf-param="_csrf_token" method-param="_method" name="csrf-token">
```

The W3C HTML validator doesn't like the `csrf-param` and `method-param` attributes on this tag. It can be happy however with something like this:

```html
<meta charset="UTF-8">
<meta content="12345" name="csrf-token">
```

Here's a sample HTML document that you can validate on https://validator.nu by using the Text Field input option:

```html
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
<meta charset="UTF-8" content="12345" csrf-param="_csrf_token" method-param="_method" name="csrf-token">
</head>
<body>
<p></p>
</body>
</html>
```

**Comment by josevalim** [comment]
Unfortunately changing it would be a backwards incompatible change, so your best option in this case is to roll your own meta tag. We can consider deprecating it too but I am not sure if it is worth pushing people through it. :( Thanks!

**Comment by jaimeiniesta** [comment]
Thanks, one way to generate our own meta tags is using this:

```html
<meta charset="UTF-8">
<meta content="<%= get_csrf_token() %>" name="csrf-token">
```

Which generates valid HTML - but we would be missing the `csrf-param="_csrf_token" method-param="_method"` part, which are invalid attributes, and I'm not sure they're needed in current Phoenix (1.5.9).

I'm not sure if we need those `csrf-param` and `method-param` attributes or if it's safe to omit them, where can I read more about why and where are they needed? I'm asking because you mentioned they're needed for backwards compatibility but maybe they are not needed in Phoenix 1.5.9?

**Comment by josevalim** [comment]
I don't think they are used anywhere indeed. We are releasing phoenix_html 3.0 in a week or two, so it is a perfect opportunity to fix this.
