### ISSUE TITLE
Retag v2.14.1, without the extra "." in the version number

### ISSUE THREAD

**Issue by gcauchon** [phoenixframework/phoenix_html#295]
I tried to update to the latest version, `v2.14.1`, but got the following error on `npm install`

```shell
> npm install --prefix assets
npm ERR! code 1
npm ERR! Command failed: git checkout v2.14.1
npm ERR! error: pathspec 'v2.14.1' did not match any file(s) known to git
```

It looks like an extra `.` was added by mistake in the tag version…

https://github.com/phoenixframework/phoenix_html/releases/tag/v.2.14.1

**Comment by josevalim** [comment]
Done, thanks for reporting!
