### ISSUE TITLE
multiple_select HTML.safe put_assoc

### ISSUE THREAD

**Issue by matteo-gheri-pocketworks** [phoenixframework/phoenix_html#297]
Hello everyone,

I just notice that the issue has not been auto-reopened thus I create this new issue.
As enoliglesias, I have problems with the HTML.safe protocol (for the category model) when I try to update the model with invalid date, thus redirect to the edit page with changeset errors.

```
<%= multiple_select f, :categories, 
      entities_for_select(@categories, :name), 
      selected: Enum.map(selected_categories, &(&1.id)),
      class: "form-control select2" %>
<%= error_tag f, :categories %>
```

I've inspected both 'entities_for_select' and 'Enum.map(selected_categories, &(&1.id))' and they return the correct values even when I get the error. Indeed at the moment I resolved the issue just using "plain" html

```
<select class="form-control select2" name="food[categories][]" multiple>
    <%= for cat <- entities_for_select(@categories, :name) do %>
        <option value="<%= Keyword.get(cat, :value) %>" <%= if Enum.any?(selected_categories, fn x -> x.id == Keyword.get(cat, :value) end), do: "selected" %>> 
            <%= Keyword.get(cat, :key) %> 
        </option>
    <% end %>
</select>
```

Somehow the issue seems related to the changeset of the food model, because If I remove this from the changeset the error disappear:

`|> put_assoc(:categories, categories, required: true)`

Same things is happening with the food's tags (another many_to_many relation). 

```
{:phoenix, "~> 1.4.10"},
{:phoenix_ecto, "~> 4.0"},
{:ecto_sql, "~> 3.1"},
{:phoenix_html, "~> 2.11"},
```

Thank you!

_Originally posted by @matteo-gheri-pocketworks in https://github.com/phoenixframework/phoenix_html/issues/174#issuecomment-609868119_

**Comment by josevalim** [comment]
Do “mix deps.update phoenix_html” and please let us know if the problem persists. If it does, please provide a small application that reproduces the error so we can take a look at it, thanks!

**Comment by matteo-gheri-pocketworks** [comment]
Hi, 

It is a bit ugly but I've created a new app and the issue persist. I've created a git repo here:

https://github.com/matteo-gheri-pocketworks/multiple_select_issue.git

if you go try to create or edit a food (http://localhost:4000/foods/1/edit) it works fine. But if you try to update a food with empty name, you get the error.

`protocol Phoenix.HTML.Safe not implemented for %MultipleSelectIssue.FoodContext.Category{}`

By the way, I recently start using elixir I do love it!!!! <3

**Comment by josevalim** [comment]
This is happening because you are using `cast_assoc` in your schema. If you are using cast_assoc, you need to use `inputs_for` in your form for handling the nesting. Otherwise, the best way to handle these relationships is to use `put_assoc` or similar. The Little Ecto Cookbook (you can find it in Ecto's readme) has some examples on associations and how to work with them. I will try to improve the error message but it may be a bit tricky.

**Comment by matteo-gheri-pocketworks** [comment]
Hello, 

I am using put_assoc not cast_assoc

```
def change_categories_if_needed(changeset, %{"categories" => categories}) do
    changeset
    |> put_assoc(:categories, categories, required: true)
  end
```

**Comment by josevalim** [comment]
Yes, apologies. I just dug a deep further. Here is the issue: https://github.com/matteo-gheri-pocketworks/multiple_select_issue/blob/42f8fece4b8befea7d7a39c2f35d86e4fc1e3755/lib/multiple_select_issue/food_context.ex#L62

You are overwriting the params, converting them from their natural data to structs. This messes up the form later on. If you do the conversion but without changing params, either by doing the conversion inside the schema or by passing the category as arguments to changeset, again, without changing the params in place, you should be good.

**Comment by matteo-gheri-pocketworks** [comment]
Ah I see, thank you so much I'll fix it!
