### ISSUE TITLE
Versioned released on NPMJS not in sync

### ISSUE THREAD

**Issue by jnbt** [phoenixframework/phoenix_html#298]
First of all: thanks for the great work ✨ 

I'm currently experimenting with our build pipeline and would like to completely split up the Erlang/Elixir-based software from the NodeJS-based software. Therefor I wanted to switch from a locally provided NPM module (`file:../deps/phoenix_html`) to a NPMJS served version.

During this attempted I discovered that the versions published on NPM are not in sync with the ones published on hex.pm. See the comparison table below.

In theory this only a minor flaw as there had not been any changes to the bundled JS since `v2.13.2`, so basically using `2.13.2` from NPM is compatible to using `2.14.1` from hex.

For me this was not directly clear, so I thought we needed to rely on loading the JS from the Elixir package. This leads to my questions:

1. I personally would like to have version numbers in sync. Could you release the `2.14.1` on NPMJS?
2. Would you accept a PR with some automatic release? E.g. Travis could publish a new build to NPM for every tagged release in the repo. Or a simpler approach: A `Makefile` which build and release the hex and NPMJS package together.

### Comparision

Version | hex.pm | npmjs.com |
--------| ------- | ----------- |
1.0.0   | ✅ | |
1.0.1   | ✅ | |
1.1.0   | ✅ | |
1.2.0   | ✅ | |
1.2.1   | ✅ | |
1.3.0   | ✅ | |
1.4.0   | ✅ | |
2.0.0   | ✅ | |
2.0.1   | ✅ | |
2.1.1   | ✅ | |
2.1.2   | ✅ | |
2.2.0   | ✅ | |
2.3.0   | ✅ | |
2.3.1   | ✅ | |
2.4.0   | ✅ | |
2.5.0   | ✅ | |
2.5.1   | ✅ | |
2.6.0   | ✅ | |
2.6.1   | ✅ | |
2.6.2   | ✅ | |
2.7.0   | ✅ | |
2.8.0   | ✅ | |
2.9.0   | ✅ | |
2.9.1   | ✅ | |
2.9.2   | ✅ | |
2.9.3   | ✅ | |
2.10.0  | ✅ | |
2.10.1  | ✅ | |
2.10.2  | ✅ | |
2.10.3  | ✅ | |
2.10.4  | ✅ | ✅ |
2.10.5  | ✅ | |
2.11.0  | ✅ | |
2.11.1  | ✅ | |
2.11.2  | ✅ | |
2.12.0  | ✅ | ✅ |
2.13.0  | ✅ | |
2.13.1  | ✅ | |
2.13.2  | ✅ | ✅ |
2.13.3  | ✅ | |
2.13.4  | ✅ | |
2.14.0  | ✅ | |
2.14.1  | ✅ | |

**Comment by josevalim** [comment]
Apologies, this is really my lack of habit of pushing to npm. It should be good now. I will try to keep up and I keep forgetting we can try a plan B. Thanks for the suggestions!
