### ISSUE TITLE
Phoenix.HTML.Safe.to_iodata error during list comprehension.

### ISSUE THREAD

**Issue by Theemuts** [phoenixframework/phoenix_html#3]
In my app I have a query which gets table `A`, inner joins table `B`, and full outer joins table `C`. The data I get from this query is correct. The data is returned as follows: `[{A1, B1, C1}, {A2, B2, C2}, ...]`, at least one model per tuple is not `nil`. If I use a list comprehension with this data in a template (eg as `for data <- @data`), I get an error that the data is invalid after processing the last element; `Phoenix.HTML.Safe.to_iodata/1` is called, but the argument is `:ok` so no clause matches. 

I have managed to solve this problem by adding `def to_iodata(:ok) do [] end` and `def to_iodata(nil) do [] end`. If only the first is included, another error is raised. I have not encountered this problem with list comprehensions based on data from other queries.

**Comment by josevalim** [comment]
`:ok` is not valid iodata. You need to return binaries or char lists from your comprehension.

**Comment by Theemuts** [comment]
I'm aware of that. What I don't understand is why a performing a list comprehension with a list of tuples leads to that error in the first place. If I get the last element of the list with `List.last/1`, I do not get `:ok`, I get the final tuple of models in the list. If I use the results of any other query which fetches more than one row, I don't get the same error. I have no idea where the `:ok` is coming from.

**Comment by chrismccord** [comment]
Can you provide the exact snippet of eex code and your stack trace?

**Comment by Theemuts** [comment]
The following code snippet is the comprehension I have used, its filename is show_multi.eex. The models have been renamed to A, B, C, and D:

`<%=
for data <- @data do
  {a, b, c} = data
      IO.puts "New row"      
      unless is_nil(a) do IO.puts a.__struct__ end
      unless is_nil(b) do IO.puts b.__struct__ end
      unless is_nil(c) do IO.puts c.__struct__ end
end %>` 

This is the relevant console output for the snippet, including the error. Weirdly enough, this time I don't encounter an error due to :ok this time, but only due to nil:

`New row
Elixir.MyApp.A
Elixir.MyApp.B
New row
Elixir.MyApp.C
New row
Elixir.MyApp.C
[info] Sent 500 in 19ms
[error] #PID<0.497.0> running MyApp.Endpoint terminated
Server: xxx.xxx.xxx.xxx:4000 (http)
Request: GET /d/47f79fb5-a534-4b28-904a-f121e2532625
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.HTML.Safe.List.to_iodata/1
        lib/phoenix_html/safe.ex:28: Phoenix.HTML.Safe.List.to_iodata(nil)
        lib/phoenix_html/safe.ex:29: Phoenix.HTML.Safe.List.to_iodata/1
        (my_app) web/templates/d/show_multi.html.eex:2: MyApp.DView."show_multi.html"/1
        (my_app) web/templates/d/show.html.eex:77: MyApp.DView."show.html"/1
        (phoenix) lib/phoenix/view.ex:197: Phoenix.View.render_within/3
        (phoenix) lib/phoenix/view.ex:429: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:533: Phoenix.Controller.do_render/4
        (my_app) web/controllers/d_controller.ex:1: MyApp.DController.phoenix_controller_pipeline/2`

**Comment by chrismccord** [comment]
IO.puts returns :ok which is your issue.  You should leave logging and IO out of templates

**Comment by Theemuts** [comment]
Thank you for the advice, I've removed all IO.puts calls from the template. Unfortunately it doesn't solve my problem, I still get the same error message.

**Comment by josevalim** [comment]
The unless when not evaluated will return nil. Please make sure you return
binaries. I will improve the error message anyway.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by Theemuts** [comment]
I've been able to confirm the reason.

I've changed my template to:
`<%=
`for data <- @data do`
`  case data do`
`    {a, b, c} ->`
`      unless is_nil(a) do a.__struct__ end`
`      unless is_nil(b) do b.__struct__ end`
`      unless is_nil(c) do c.__struct__ end`
`    _ -> "ok"  end`
`end %>`


 If I set `data` to `[{nil, nil nil}]` I get an error. If I set `data` to `[]`, I don't get an error.

**Comment by josevalim** [comment]
Yes, because if the data is nil, unless won't be invoked and it will return
nil.

On Saturday, May 16, 2015, Theemuts <notifications@github.com> wrote:

> I've been able to confirm the reason.
>
> I've changed my template to:
> <%=
> for data <- @data <https://github.com/data> do
>  case data do
>  {a, b, c} ->
>  unless is_nil(a) do a.*struct* end
>  unless is_nil(b) do b.*struct* end
>  unless is_nil(c) do c.*struct* end
>  _ -> "ok" end
> end %>`
>
> If I set data to [{nil, nil nil}] I get an error. If I set data to [], I
> don't get an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix_html/issues/3#issuecomment-102633128>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by Theemuts** [comment]
Sorry, I hadn't seen your reply before writing my comment. Thanks, returning an empty string rather than nil did solve the error.

**Comment by josevalim** [comment]
No problem! Keep on opening reports like these, it shows our error messages
could be clearer in cases like this. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by Theemuts** [comment]
You're welcome! :) (Although I do feel I should really learn to ask for help on StackOverflow first rather than immediately reporting it here)
