### ISSUE TITLE
Allow to pass html attributes to a select option when the option has been generated with prompt

### ISSUE THREAD

**Issue by Malian** [phoenixframework/phoenix_html#303]
I was trying to reproduce the following html with an extra "disabled" html attribute to the first option that proposes to select a role:
```html
<select id="user_role" name="user[role]">
    <option value="" disabled>Choose your role</option>
    <option value="admin">Admin</option>
    <option value="user">User</option>
</select>
```
The doc proposes a [prompt option](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#select/4-options), so I was trying to use it:
```elixir
select(form, :role, ["Admin": "admin", "User": "user"], prompt: "Choose your role")
```
This options does not allow to generate extra html attribute so the result is the following:
```html
<select id="user_role" name="user[role]">
    <option value="">Choose your role</option>
    <option value="admin">Admin</option>
    <option value="user">User</option>
</select>
```

I find to workarounds:

1. Add the option manually:
```elixir
select(form, :role, [
[value: "", key: "Choose your role", disabled: true],
[value: "admin", key: "Admin"],
[value: "user", key: "User"])
```
2. Use an optgroup to simulate the behavior but it does not select the group label:
```elixir
select(form, :role, ["Choose your role": ["Admin": "admin", "User": "user"]])
```
To be honest I don't like these solutions. I implemented a solution in phoenix_html that allow to pass a list to the `prompt` option but I would like to have your opinion about the usefulness of this implementation before creating a pull request.

So you will be able to use the prompt option as following:
```elixir
select(form, :role, ["Admin": "admin", "User": "user"], prompt: [key: "Choose your role", disabled: true])
```
and it will generate the following code:
```html
<select id="user_role" name="user[role]">
    <option value="" disabled>Choose your role</option>
    <option value="admin">Admin</option>
    <option value="user">User</option>
</select>
```
I use the "key" key to be consistent with the current implementation.

Do you see any drawback?

**Comment by josevalim** [comment]
I like this idea. :+1: A PR is welcome! :heart:
