### ISSUE TITLE
`link(name, to: %URI{})` as a valid option

### ISSUE THREAD

**Issue by davydog187** [phoenixframework/phoenix_html#308]
I'll submit a PR if this seems like a good idea, but it would be nice for the `to:` option to accept a `%URI{}` struct as a valid option. My thought is that it would be as simple as doing a `to_string` on the URI.

We could just pass through the string to the validate step, or it could have a slightly optimized version of the validation https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/link.ex#L254

**Comment by josevalim** [comment]
Adding a `to_string` call sounds good to me. A PR is welcome!
