### ISSUE TITLE
Proposal: make `generic_input/4` publicly accessible

### ISSUE THREAD

**Issue by robinvdvleuten** [phoenixframework/phoenix_html#313]
It would be nice to have `generic_input/4` publicly accessible. It allows easier creation of custom form helpers in the spirit of this old blog post by Plataformatec (http://blog.plataformatec.com.br/2016/09/dynamic-forms-with-phoenix/). The article is using an old `input/4` helper method which seems to be removed in a newer version.

**Comment by josevalim** [comment]
The helper from that blog post is implemented in that blog post itself. It starts on the "Showing the input" section and it doesn't rely on generic_input.

**Comment by robinvdvleuten** [comment]
Totally overlooked 🤦‍♂️ thanks!
