### ISSUE TITLE
Links defined with :method opt do not respect cmd/ctrl clicks

### ISSUE THREAD

**Issue by jtormey** [phoenixframework/phoenix_html#319]
A frequently used browser feature is to click on a link while holding cmd, which opens the link in a new tab while keeping the current tab focused (supported in all major browsers).

When a `:method` opt is added to the `link` helper function, this behavior breaks, and the link opens in the current tab as if cmd wasn't held down. If `target: "_blank"` is added to the `link`, cmd + click behaves as expected regardless of the `:method`. Can be observed in standard templates as well as with LiveView.

Reproducible with:

```ex
<%= link "Link with method", to: Routes.page_path(@conn, :post_link), method: :post %>
```

Happy to look into fixing this if relevant!

**Comment by josevalim** [comment]
I don't think we can fix this because we cannot submit a POST operation by opening another tab. The best we can do is to add some information to the docs. Can you please prepare such PR? Thanks!

**Comment by jtormey** [comment]
I played around with this, and found that a fix is possible by setting `target = "_blank"` on the hidden form created by `phoenix_html`. The click handler could add the target property conditionally, based on whether the `metaKey` or `shiftKey` event properties are true.

The behavior mirrors a normal link exactly in Chrome and Safari, however it's *slightly* different for FireFox (a new tab always opens and is focused, rather than an unfocused tab for cmd + click and a new window for shift + click). Still, pretty close!

If this seems like a worthwhile change, mind if I open a PR?

**Comment by jtormey** [comment]
> If target: "_blank" is added to the link, cmd + click behaves as expected regardless of the :method.

It looks like the form element adopts the link target ([source](https://github.com/phoenixframework/phoenix_html/blob/69c863907dc1077b9ac7b3c2b74c787909efa390/priv/static/phoenix_html.js#L38)), which explains why cmd/shift+click works in this case.

**Comment by josevalim** [comment]
I think it is worth giving it a try. PR please!
