### ISSUE TITLE
:value option for datetime_local_input not working

### ISSUE THREAD

**Issue by francis-perbs** [phoenixframework/phoenix_html#326]
When using datetime_local_input inside a form_for, the :value atom does not set the default value of the form field. In this code snippet, the datetime_local_input form field does not show any value when the screen is rendered.

```
<div class="form-group row">
    <%= label f, :input_dateTimeOut, class: "col-2 col-form-label" do %>
      Date/Time Out
    <% end %>
    <div class="col-3">
      <%= datetime_local_input f, :input_dateTimeOut, value: @attendance.input_dateTimeOut, class: "form-control form-control-sm" %>
    </div>
    <%= error_tag f, :input_dateTimeOut %>
  </div>
```

But looking at the source code its should support the :value option.
```
def datetime_local_input(form, field, opts \\ []) do
    value = Keyword.get(opts, :value, input_value(form, field))
    opts = Keyword.put(opts, :value, datetime_local_input_value(value))

    generic_input(:"datetime-local", form, field, opts)
  end
```

**Comment by josevalim** [comment]
@francis-perbs can you check the HTML source? We do use the value. My hunch is that your value is invalid and the browser is ignoring it.

**Comment by francis-perbs** [comment]
@josevalim I tried to replace datetime_local_input with datetime_select or text_input and it displays the correct value.
The value passed to the function was a datetime value from db that was converted using tz_datetime.original_datetime.
I am also using chrome with the latest update.

**Comment by francis-perbs** [comment]
@josevalim  I've checked the HTML source, the value being passed is not the same format required by datetime_local_input.

Got it working now. Thanks.
