### ISSUE TITLE
Add support for nested form fields

### ISSUE THREAD

**Issue by achempion** [phoenixframework/phoenix_html#328]
Hi,

I would like to add support for nested form fields

The result I want to be able to generate:
```html
<input id="feedbacks_42_rating" name="feedbacks[42][rating]" type="text" value="">
```

The call would look like
```elixir
text_input(:feedbacks, [42, :rating])
```

We need to modify methods responsible for generating [`id`](https://github.com/phoenixframework/phoenix_html/blob/v2.14.3/lib/phoenix_html/form.ex#L503) and [`name`](https://github.com/phoenixframework/phoenix_html/blob/v2.14.3/lib/phoenix_html/form.ex#L537) along with adding a new specification for [`field`](https://github.com/phoenixframework/phoenix_html/blob/v2.14.3/lib/phoenix_html/form.ex#L259) type.

What do you think?

**Comment by josevalim** [comment]
It is already supported via `inputs_for`. If that is not quite what you want, you can mirror whatever `inputs_for` does with your own code. :)
