### ISSUE TITLE
v2.14.3 is not published to NPM

### ISSUE THREAD

**Issue by egze** [phoenixframework/phoenix_html#340]
Can you please publish it?

Is it worth looking into automation with GitHub actions?

**Comment by josevalim** [comment]
There are no changes in the JS though. We skip some of the patch releases if the JS doesn't change at all. Thanks!

**Comment by egze** [comment]
Thanks @josevalim !

For use case when installing with npm this is a bit confusing to see that the hex and npm versions don't match. Can you think about publishing anyway just to not cause confusion?

**Comment by josevalim** [comment]
Sounds fair, done!
