### ISSUE TITLE
`Phoenix.HTML.Form.select/4` `:selected` option considers params, but not data

### ISSUE THREAD

**Issue by endersstocker** [phoenixframework/phoenix_html#342]
Before the `:selected` option was added to `Phoenix.HTML.Form.select/4` I was able to do select a default with `nil` like so:
```elixir
<%= select f, :category_id, ids_by_name(@categories) ++ [{"Other", nil}],
      class: "form-control" %>
```

With the addition of the `:selected` option, I would expect to need this for the same behavior:
```elixir
<%= select f, :category_id, ids_by_name(@categories) ++ [{"Other", ""}],
      selected: "",
      class: "form-control" %>
```

However, I am required to do this:
```elixir
<%= select f, :category_id, ids_by_name(@categories) ++ [{"Other", ""}],
      selected: f.data.category_id || "",
      class: "form-control" %>
```

It would be reasonable for `:selected` to check the params, _then the data,_ before falling back to the default.

**Comment by josevalim** [comment]
It is work as intended, see this issue for a longer discussion: https://github.com/phoenixframework/phoenix_html/issues/32

In a nutshell, we need to give users control to not check the data at all, because the data may be in a shape that is not appropriate.

**Comment by endersstocker** [comment]
To clarify, if I don't use the `:selected` option, then `select` uses the params, then data. As soon as I add the `:selected` option, the data is ignored.
