### ISSUE TITLE
dialyzer error upgrading to 3.0.0

### ISSUE THREAD

**Issue by brianmay** [phoenixframework/phoenix_html#345]
The following code:

```
<%= form_for @changeset, Routes.user_path(@conn, :update, @user), fn f -> %>     
  ...
<% end %>
```

Gives the dialyzer error:

```
lib/robotica_hello_web/templates/user/edit.html.eex:0:no_return
Function edit.html/1 has no local return.
________________________________________________________________________________
lib/robotica_hello_web/templates/user/edit.html.eex:3:call
The function call will not succeed.

Phoenix.HTML.Form.form_for(any(), any(), (_ -> {:safe, [any(), ...]}))

will never return since the success typing is:
(any(), any(), Keyword.t()) :: %Phoenix.HTML.Form{
  :action => _,
  :data => %{atom() | binary() => _},
  :errors => [{_, _}],
  :hidden => [{_, _}],
  :id => binary(),
  :impl => atom(),
  :index => nil | non_neg_integer(),
  :name => binary(),
  :options => [{_, _}],
  :params => %{binary() => _},
  :source => _
}

and the contract is
(Phoenix.HTML.FormData.t(), String.t(), Keyword.t()) :: Phoenix.HTML.safe()
```

So it looks like the 3rd argument should be a keyword list.

But the documentation says it should be a function. https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html:

```
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
```

**Comment by brianmay** [comment]
I am still seeing this error with version 3.0.1

https://github.com/brianmay/robotica-elixir/runs/3343513388?check_suite_focus=true

**Comment by brianmay** [comment]
@josevalim What do we need to do to fix this? Unfortunately I cannot reopen the bug report.

**Comment by josevalim** [comment]
A PR is welcome!

**Comment by jcrevits** [comment]
I'm not 100% sure this is fixed yet. I fixed the spec in the lib itself but I'm still seeing dialyzer errors in my project even with 3.0.2. I'm fairly new to committing to an Elixir lib so bear with me :)

**Comment by brianmay** [comment]
I can confirm that version 3.0.2 has fixed the problem for me. As in the CI now passes. Thanks!
