### ISSUE TITLE
:disabled attribute does not update when assigns change

### ISSUE THREAD

**Issue by roylez** [phoenixframework/phoenix_html#346]
```
<%= submit "Update", disabled: @disabled %>
```

when `disabled` assign is updated, the attribute is not add/removed accordingly.

**Comment by josevalim** [comment]
I assume you meant to fill an issue on Phoenix LiveView, as Phoenix HTML does not know anything about updates. Please open up a report there and try to provide as much information as you can, such as versions are a small LiveView that reproduces the issue. Thanks.
