### ISSUE TITLE
Issues with line breaks at the end of a tag

### ISSUE THREAD

**Issue by isakemanuel** [phoenixframework/phoenix_html#351]
For quite some time I was stuck with an error saying `missing terminator: end (for "fn" starting at line 298)`. By trial and error I finally found out I had to change this

```
<%= form_for @changeset,
    "#",
    [
      id: "form",
      phx_change: :update_form,
      phx_auto_recover: "ignore"
    ], fn f -> 
  %>
```
into this

```
<%= form_for @changeset,
    "#",
    [
      id: "form",
      phx_change: :update_form,
      phx_auto_recover: "ignore"
    ], fn f -> %>
```
in order for the template to compile. Should the first example work the same as the second one?

**Comment by josevalim** [comment]
It should work. Is this a HEEx template, LEEx template, or does it happen with both?

Also, please remember to fill in the issues template when doing future reports. :)

**Comment by isakemanuel** [comment]
> It should work. Is this a HEEx template, LEEx template, or does it happen with both?

It is a HEEx template. I do not know if it happens with LEEx templates as well.

> Also, please remember to fill in the issues template when doing future reports. :)

Sorry! I didn't know there was one. Usually on other repositories the issue template appears when creating a new issue, but now it was just blank. Where can I find it? .github/ISSUE_TEMPLATE looks empty

**Comment by josevalim** [comment]
Ignore me, I thought this was filled on the LiveView repo :)

**Comment by josevalim** [comment]
Fixed in Elixir master, thank you!
