### ISSUE TITLE
Proposal: add add/remove buttons to make inputs_for dynamic

### ISSUE THREAD

**Issue by ogabriel** [phoenixframework/phoenix_html#353]
# Proposal: add add/remove buttons to make inputs_for dynamic

## Summary

Hi.

I was refactoring some old code, and noticed that the implementation for `inputs_for/4` didn't allow for a dynamic remove and addition of items on the collection, which is understandable, as such implementation would require some JavaScript code and some added elements to make it work.

After trying some other external libraries and implementing the function on my own, I thought that maybe other people can make use of this functionality, as it's a fairly common on other form building libraries for other languages.

## Background

If you go through the elixir forum, you can find people having related problems, there aren't too many people requesting this functionality, but I still think it would be a great addition.

Also, all current libraries that implement this function have some undesirable quirks that can cause some headache or are unmaintained (I will probably reference them also as an inspiration on the pull request, if accepted).

## Proposal

I already have an implementation of such feature coded. It's fairly self-contained and needs only a few lines of code, if implemented directly on the `phoenix_html` it will have even fewer lines, currently there are around 40 JavaScript lines, 25 elixir lines and 20 eex lines.

It basically creates a `template` tag that contains the actual code for the "nested form", and each time the user clicks on the add button, it calculates the current last index and inserts a new instance of the "form" replacing the old index.

The deletion of items on the list is based on a wrapped div outside each "nested form", and removes the entire element.

## Conclusion

If my proposal is accepted, I can port my code to the official code and open a pull request.

## Related issues

Looking through old issues, there seems to be a "issue" against a implementation of a type of array input, which is fairly [related](https://github.com/phoenixframework/phoenix_html/issues/214#issuecomment-386912591), to the feature I'm proposing.

**Comment by chrismccord** [comment]
This sounds like a great external library or blog post so other folks can take advantage of your work. We don't intend to expand the very limited javascript capabilities of `phoenix_html` and dynamic features will rather be developed on the LIveView side. That said, your solution for non LiveView users sounds like a great option for folks. Thanks!

**Comment by MarvinKweyu** [comment]
@ogabriel , do you have a link to your blog post or code to share?

**Comment by ogabriel** [comment]
@MarvinKweyu my plan was to extract the code I developed to a library, but I ended up never doing it, but I still have plans to develop it, when I finish it, I will post on this issue

**Comment by MarvinKweyu** [comment]
Sure @ogabriel . I'd like to look at and possibly contribute. If you'd be open, share the project link.
