### ISSUE TITLE
Npm version doesn't match Hex

### ISSUE THREAD

**Issue by egze** [phoenixframework/phoenix_html#354]
Can you please push all npm versions (at least the 3.0.3) even if there were no changes to the js/css? We install all npm libraries from npmjs and have a check that their hex counterparts should have an exact version match.

Npm (3.0.0): https://www.npmjs.com/package/phoenix_html
Hex (3.0.3): https://hex.pm/packages/phoenix_html

**Comment by josevalim** [comment]
Done!
