### ISSUE TITLE
Search function of documentation (hexdocs.pm) is broken

### ISSUE THREAD

**Issue by Fabi755** [phoenixframework/phoenix_html#37]
Hey,
I'm not sure if I am right here but the search is not working on the hexdocs site.

Reproduce: 
1. Call https://hexdocs.pm/phoenix_html/Phoenix.HTML.html
2. Click in search field
3. Type some word/letters
4. Press enter
... nothing

OS: Windows 8
Browser: FireFox (40.0.3)

Thanks,
Fabi

**Comment by chrismccord** [comment]
I think this is something on ex_docs end, but I'll make sure to rebuild the docs when we push a new release soon.

**Comment by josevalim** [comment]
New docs pushed.
