### ISSUE TITLE
Release v3.2.0 to npm

### ISSUE THREAD

**Issue by egze** [phoenixframework/phoenix_html#370]
hex.pm has the `3.2.0` version, while npmjs is still on `3.1.0`.

Please publish to npm to avoid confusion, as some people (at least myself) install frontend packages from npm.

P.S. On another note, since this has come up several times - should publishing happen automatically from CI? I could work on it.

**Comment by josevalim** [comment]
Pushed. I don't think we need CI. It was my bad. I keep thinking we only release a new version when something changes, but that's not the case.
