### ISSUE TITLE
v3.2.0 commit missing from master

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix_html#371]
The version 3.2.0 commit is missing from master: 4dc4e45b0e06c6fe26f2e91136fe581171e65e98. I also can't find which branch this commit was made on since there's no 3.x branch either. When viewing master, it looks like the current version of phoenix_html is 3.2.0. I'm not sure if I'm missing something, but I thought it was worth bringing up. :grin:

**Comment by josevalim** [comment]
It failed to push when it happened. The commit is now up but not according to history.
