### ISSUE TITLE
Phoenix.HTML goes slim

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_html#372]
With HEEx, many of the functions in this module have lost their purpose. Therefore, our goal is to remove redundant functionality from `Phoenix.HTML`. In particular, `Phoenix.HTML.Format`, `Phoenix.HTML.Link`, and `Phoenix.HTML.Tag` should be deprecated. To do so, we need to move some of the required functionality around:

  * [x] `Phoenix.HTML.Tag.attributes_escape` will be moved to `Phoenix.HTML`
  * [x] `Phoenix.HTML.Link.button` will be broken into `Phoenix.HTML.link_attributes/2`
  * [x] Import `Phoenix.Controller.get_csrf_token()` to `use MyAppWeb, :view` and use it instead of `csrf_meta_tag` in templates
  * [x] `Phoenix.HTML.Link.link/2` should be moved to `Phoenix.LiveView.Helpers.link/1` function component with a unified API
  * [x] Change `mix phx.new` to only import `Phoenix.HTML` and `Phoenix.HTML.Form`
  * [x] Soft deprecate `Phoenix.HTML.{Format, Link, Tag}`

There are some open discussion points:

  * [ ] Should we have a replacement for `Phoenix.HTML.Form`?
  * [ ] If we do have one, should `Phoenix.HTML` even exist? Perhaps it should be a `phoenix_html_safe` project and the existing `Phoenix.HTML` module is part of `Phoenix.View.HTMLHelpers` or similar?

**Comment by leandrocp** [comment]
Hey @josevalim is this issue open for PRs? I could give a hand.

**Comment by josevalim** [comment]
I think we still have to figure out some of those but we can definitely go ahead with "Move Phoenix.HTML.Tag.csrf_token_value/0-1 to Phoenix.HTML (convert csrf_meta_tag and csrf_input_tag to examples)" and then change the generators to use csrf_token_value.

**Comment by leandrocp** [comment]
> I think we still have to figure out some of those but we can definitely go ahead with "Move Phoenix.HTML.Tag.csrf_token_value/0-1 to Phoenix.HTML (convert csrf_meta_tag and csrf_input_tag to examples)" and then change the generators to use csrf_token_value.

Seems like "Move Phoenix.HTML.Tag.tag/2 and content_tag/3 to Phoenix.HTML" has no blocks and should be good for a PR too.

**Comment by josevalim** [comment]
Most of it is done!

**Comment by sevab** [comment]
Upgrading a phoenix app, and `Phoenix.HTML.Format.text_to_html` is now obviously undefined.
How do I get to replicate this functionality in latest Phoenix version now that `text_to_html/1` is gone?

**Comment by SteffenDE** [comment]
@sevab the functions were moved to the `:phoenix_html_helpers` library, see the changelog: https://github.com/phoenixframework/phoenix_html/blob/main/CHANGELOG.md#v400-2023-12-19

https://github.com/phoenixframework/phoenix_html_helpers/blob/main/lib/phoenix_html_helpers/format.ex
