### ISSUE TITLE
Checkboxes generates same ID

### ISSUE THREAD

**Issue by ryvasquez** [phoenixframework/phoenix_html#380]
Hi Team 👋 

First of all thanks for all great effort!

Using multiple [checkbox/3](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#checkbox/3) checkboxes emits warning from Liveview if you dont provide a custom ID, I also noticed that this doesnt happen when using multiple `radio/4` due since appending the value to the ID

However I'm not sure if the team considering this scenario as valid, some form with multiple checkboxes can be grouped by name and pass the value as an array in the controller.

```
<.form let={f} for={@changeset} id="test-form">
    <%= checkbox(f, :famous, value: "A") %> Value A
    <%= checkbox(f, :famous, value: "B") %> Value B
</.form>
```

Will results to 
```html
<form action="#" method="post" id="test-form">
    <input name="_method" type="hidden" value="put">
    <input name="question[famous]" type="hidden" value="false">
    <input id="test-form_famous" name="question[famous]" type="checkbox" value="true"> Value A
    <input name="question[famous]" type="hidden" value="false">
    <input id="test-form_famous" name="question[famous]" type="checkbox" value="true"> Value B
</form>
```

And Liveview will throw error something like
<img width="1439" alt="Screen Shot 2022-05-04 at 7 32 41 PM" src="https://user-images.githubusercontent.com/8102493/166673359-c5784ca8-1cb9-4417-8b4a-26cdbdc19593.png">

Please let me know if there is also same discussion happened before. 
If the team thinks the case is valid, im happy to throw a Pull Request to address the said issue above.

**Comment by josevalim** [comment]
Yes, this is expected, since the checkboxes are usually for "boolean" values. In the example above, one would typically use a radio button or a multiple select. But if you want to keep with checkboxes, then you need to pass the ID option :)

**Comment by ryvasquez** [comment]
@josevalim I see, totally makes sense! Thankyou for the explanation, I will close this issue now 👍

**Comment by ryvasquez** [comment]
@marcandre Thankyou very much! 👏
