### ISSUE TITLE
name attribute of `multiple_select/4` inconsistent with `input_name/2`, which results in `MyApp.ErrorHelpers.error_tag/2` setting an incorrect `phx_feedback_for` attribute

### ISSUE THREAD

**Issue by linusdm** [phoenixframework/phoenix_html#386]
The name attribute of the select tag generated with `Phoenix.HTML.Form.multiple_select/4` contains a trailing `[]`. This is inconsistent with the name that is generated with `Phoenix.HTML.Form.input_name/2`.

The problem arises when you use the default generated `MyApp.ErrorHelpers.error_tag/2` which relies on `input_name/2` to add `phx_feedback_for`. Hence, the trick to hide error messages of fields that have not been focussed yet doesn't work for multi-selects.
Manually adding the brackets to the name when using the `error_tag/2` function for a multiple-select does fix the problem, so I'm quite confident this is the root cause of this problem. In iex this discrepancy can be easily shown:

```elixir
iex> Phoenix.HTML.Form.multiple_select(:test, :field, []) |> Phoenix.HTML.safe_to_string()
"<select id=\"test_field\" multiple=\"\" name=\"test[field][]\"></select>"

iex> Phoenix.HTML.Form.input_name(:test, :field)
"test[field]"
```

I see the trailing brackets are added on purpose, and are required to function properly [here](https://github.com/phoenixframework/phoenix_html/blob/428801f48f19284583a94f68d211826d583ef33d/lib/phoenix_html/form.ex#L1351).

If this actually is a bug (maybe I have a wrong expectation), I'd be happy to help with a PR, if someone can nudge me in the right direction.

**Comment by josevalim** [comment]
Yes, the [] is required because we need to signal the server that multiple values will be set and they will be accumulated as a list. The fix, IMO, is to change the logic on `phx_feedback_for` to search for both `name` and `name[]`. Can you please open up an issue or send a PR to LiveView? Thank you! :heart:

**Comment by linusdm** [comment]
Ok, I can do that.

But it still feels a bit strange that `input_name/2` and the generated name for this tag are not consistent. All logic depending on `input_name/2` now suddenly has to be aware of this possible difference.

**Comment by josevalim** [comment]
There is no other way we can tackle this though. We could parameterize `input_name` on the input type too, but I don't think that's necessarily helpful.

**Comment by linusdm** [comment]
No, you're right. The simplicity of `input_name/2` should be kept, without having to pass down the type of the element.

I'll have a go at it. Thanks for your response, I'm learning a lot this way. 💜
