### ISSUE TITLE
Add datalist ?

### ISSUE THREAD

**Issue by ndrean** [phoenixframework/phoenix_html#391]
Could we add a special input "datalist_input"  in Phoenix.HTML.Form? 

```elixir
def datalist_input(opts, [do: _] = block_options) do
    content_tag(:datalist, opts, block_options)
end

def option_input(user) do
    content_tag(:option, "", value: user)
end
```

It can be documented by giving an example of how to use it in conjunction with an input. For example, below on change of the input with the key `:user`, we have a "local" debounced query for a matching "user" and we populate the datalist with the results passed as assigns with the key  `:users`:

```elixir
<%= text_input(f, :user, 
    phx_change: "search", 
    phx_target: @myself, 
    phx_debounce: "500", 
    list: "datalist", 
    placeholder: "enter an email") %>

 <%= datalist_input(id: "datalist") do %>
   <%= for user <- @users do %>
      <%= option_input(user) %>
   <% end %>
<% end %>
```

**Comment by josevalim** [comment]
With HEEx, we are actually moving away from such style of functions, so we don't have plans to move in this direction for the moment.

**Comment by ndrean** [comment]
ok, so how do you use a datalist with the function `.form` since everything is interpolated?
