### ISSUE TITLE
Nested changeset validation does not play nice with `form_for`

### ISSUE THREAD

**Issue by Sleepful** [phoenixframework/phoenix_html#394]
It is a little hard to display all the code since there are a lot of moving parts but I will make an attempt. The interesting bit is that my Ecto schemas work perfectly for creating the resource, but if the associated schema fails validation then the resulting changeset (with the information about invalid fields) is not accepted by `form_for`.

Most of the code is standard `mix phx.gen.html` boilerplate:

**category.ex**
```elixir
defmodule App.Classifier.Category do
  use Ecto.Schema
  import Ecto.Changeset
  schema "categories" do
		# redacted for brevity
    has_many :categories_multiselect, App.CategoryMultiselect
  end

  @doc false
  def changeset(category, attrs) do
    category
    |> cast(attrs, [:name, :required, :user_id, :type])
    |> validate_required([:name, :required, :user_id, :type])
    |> cast_assoc(:categories_multiselect)
  end
```

**category_multiselect.ex**
```elixir
defmodule App.CategoryMultiselect do
  use Ecto.Schema
  import Ecto.Changeset

  schema "categories_multiselect" do
		# redacted for brevity
    belongs_to :category, App.Classifier.Category
  end

  @doc false
  def changeset(category_multiselect, attrs) do
    category_multiselect
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end
```

**category_controller.ex**
```elixir
  def create(conn, %{"category" => category_params}) do
    user = conn.assigns[:current_user]
    category_params = Map.put_new(category_params, "user_id", Map.get(user, :id))
    IO.puts("PARAMS")
    IO.inspect(category_params)
    case Classifier.create_category(category_params) do
      {:ok, category} ->
        conn
        |> put_flash(:info, "Category created successfully.") 
		# if there are no validation errors
		# this succeeds!
        |> redirect(to: Routes.category_path(conn, :show, category))

      {:error, %Ecto.Changeset{} = changeset} ->
        types = Category.type_values
        IO.puts("INVALID CHANGESET")
        IO.inspect(changeset) # I include the output of this down below!
 		# the code gets here right before the error stacktrace
        render(conn, "new.html", changeset: changeset, types: types)
    end
  end
```
**new.html.heex**
```elixir
<%= render("form.html", Map.put(assigns, :action, Routes.category_path(@conn, :create))) %>
```

Here is how I am using `form_for` in my app:

**form.html.heex**
```
<.form let={f} for={@changeset} action={@action}>
...
         # this is the line that the error stack mentions in `form.html.heex`:
          <%= text_input(f, :categories_multiselect,
            "x-bind:name": "`#{f.name}[categories_multiselect][${i}][name]`"
          ) %>
...
</.form>
```

Here is the changeset that breaks the `form_for`, the reason why it breaks `form_for` is because of the `#Ecto.Changeset` found in `#Ecto.Changeset.changes.categories_multiselect[i].#Ecto.Changeset`, it seems that there should not be `#Ecto.Changeset` inside the `changes` key, here's the `IO.inspect(changeset)` for the changeset in my app:
```elixir
#Ecto.Changeset<
  action: :insert,
  changes: %{
    categories_multiselect: [
      #Ecto.Changeset<
        action: :insert,
        changes: %{},
        errors: [name: {"can't be blank", [validation: :required]}],
        data: #App.CategoryMultiselect<>,
        valid?: false
      >,
      #Ecto.Changeset<
        action: :insert,
        changes: %{name: "TwoFail"},
        errors: [],
        data: #App.CategoryMultiselect<>,
        valid?: true
      >
    ],
    name: "This should fail",
    type: :multiselect,
    user_id: 2
  },
  errors: [],
  data: #App.Classifier.Category<>,
  valid?: false
>
```
Here is the stacktrace for the error:
```elixir
Request: POST /category
** (exit) an exception was raised:
    ** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: #Ecto.Changeset<action: :insert, changes: %{}, errors: [name: {"can't be blank", [validation: :required]}], data: #App.CategoryMultiselect<>, valid?: false>
        (phoenix_html 3.2.0) lib/phoenix_html/safe.ex:81: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 3.2.0) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:151: Phoenix.HTML.html_escape/1
        (elixir 1.14.1) lib/keyword.ex:1107: Keyword.update!/4
        (phoenix_html 3.2.0) lib/phoenix_html/form.ex:830: Phoenix.HTML.Form.generic_input/4
        (app 0.1.0) lib/app_web/templates/category/form.html.heex:37: anonymous fn/3 in AppWeb.CategoryView."form.html"/1
        (phoenix_live_view 0.17.12) lib/phoenix_live_view/engine.ex:124: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
        (phoenix_live_view 0.17.12) lib/phoenix_live_view/engine.ex:140: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
        (phoenix 1.6.13) lib/phoenix/controller.ex:772: Phoenix.Controller.render_and_send/4
        (app 0.1.0) lib/app_web/controllers/category_controller.ex:1: AppWeb.CategoryController.action/2
        (app 0.1.0) lib/app_web/controllers/category_controller.ex:1: AppWeb.CategoryController.phoenix_controller_pipeline/2
        (phoenix 1.6.13) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
        (app 0.1.0) lib/plug/debugger.ex:136: AppWeb.Endpoint."call (overridable 3)"/2
        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
        (phoenix 1.6.13) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /Users/home/Code/WordDatabase/app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/home/Code/WordDatabase/app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/home/Code/WordDatabase/app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

That's it 🥲 

I think there's a question here to be made, something along the lines of:
> *"Is it Phoenix.HTML responsibility to handle these changesets correctly or should the user make sure the changeset complies to the shape that `form_for` expects?"*

 I am submitting this issue under the assumption that 

> *yes, it is Phoenix.HTML responsibility to handle the various ways in which Ecto creates changesets*

because from my experience Phoenix.HTML *wants* to interop with Ecto seamlessly; but correct me if I am wrong.

**Comment by Sleepful** [comment]
if I change 
```
          <%= text_input(f, :categories_multiselect)%>
```
to use a string instead of an atom, trying to circumvent the error:
```
          <%= text_input(f, "categories_multiselect")%>
```      
Then I get an error in a completely different package, here:

https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/html.ex#L123

So it is funny because I can't step outside of the lines, but also difficult to figure out how to put things together because the code steps through many packages

**Comment by Sleepful** [comment]
I no longer get the error if I stop trying to use the form, like this:

```
          <%= text_input(:categories_multiselect, "some_name")%>
```

But this stops me from using the changeset. Is this the solution?

**Comment by josevalim** [comment]
I don’t think this is a bug. How could form know how to convert a list of change sets into strings? If you pass an integer to datetime input, you will get similar errors too. In those cases, you need to convert the change set values into the input.

**Comment by Sleepful** [comment]
It's strange imo, using `inputs_for` then *it knows* how to convert a list of change sets into strings:
```
        <%= for fp <- inputs_for(f, :categories_multiselect) do %>
          <%= text_input(fp, :name) %>
        <% end %>
```
This works for my case. However, this only works once a changeset has been created with invalid errors. So I becomes impossible to use `text_input` to enter new values and *also* use the same `text_input` to show the user validation errors.

**Comment by josevalim** [comment]
Yes, because the goal of inputs_for is exactly to deal with this type of input. As `datetime_input` knows how to deal with date inputs and so on.

**Comment by Sleepful** [comment]
the problem with `inputs_for` is that I cannot use it to create *new* values for a *new* resource, it only works in the case of having already-existing values. This is *unlike* the other functions, for example I can use `text_input` for new values and also for values that already exist.

**Comment by Sleepful** [comment]
So the solution seems to be using two types of `text_input`

1. `text_input` for new values
2. `text_input` for pre-existing values

It is a little similar to what you say, treating the values as different types, but it was not intuitive to figure out because the values are going to end up on the same place. This makes it a little strange to reason about because other inputs treat new values and existing values as the same type.

I also see no way around this, fields for pre-existing values are going be created on the server while fields for new values are going to be dynamically created in the client side. They are very different even though on the UI they want to look the same.

So here is what I ended up doing, there's some AlpineJS in there that can be ignored but it gives an idea of the situation I am talking about:

```elixir
  <.dynamic_tag
    name="div"
    x-data={ # javascript to keep track of both inputs 
      "{
        radio: '#{Map.get(f.source.changes, :type, "null")}',
        count: 0,
        existing: #{Map.get(f.source.changes, :categories_multiselect, []) |> length },
        get remove() { this.count ? this.count-- : $refs[`input${this.existing}`].remove() || this.existing--  }
      }"}
    class="space-y-2"
  >
        <%= for {fp, i} <- inputs_for(f, :categories_multiselect) |> Enum.with_index(1) do %>
          <%= text_input(fp, :name, "x-ref": "input#{i}") %> 
			# pre-existing values end up here
          <%= error_tag(fp, :name) %>
        <% end %>
        <template x-for="i in count" class="space-y-2" x-bind:key="i">
          <%= text_input(:category, :categories_multiselect,
            "x-bind:name": "`#{f.name}[categories_multiselect][${existing+i-1}][name]`"
          ) %>
		# new values are dynamically created, can't pass the form struct to this text_input
        </template>
	# the downside is a lot of code to keep order between the two types inputs
        <button type="button" x-on:click="count++">+ Add value</button>
        <button type="button" x-show="count>0 || existing>0" x-on:click="remove">- Remove value</button>
  </.dynamic_tag>

```
