### ISSUE TITLE
Plans for eventual v4.0

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_html#399]
With HEEx, most of the functionality in this project lost relevance. New Phoenix apps only `import Phoenix.HTML` and nothing more.

For Phoenix.HTML v4.0, we want to keep only the functionality that makes sense. Which is:

* `Phoenix.HTML`
* The low-level blocks from `Phoenix.HTML.Form` (the struct and a couple functions)
* The `Phoenix.HTML.FormData` and the `Map` implementation (Atom and Plug.Conn will be moved)
* The `Phoenix.HTML.Safe` protocol, implementations, the underlying HTML engine

However, in order to avoid breaking current applications, we will move all functionality to a project called `phoenix_html_helpers` and move them to the `PhoenixHTMLHelpers` namespace. This migration means:

* [x] We will move all modules, except the ones listed above, to `PhoenixHTMLHelpers` (`Form` will exist in both)
* [x] We will remove the "action" field from the Form struct
* [x] `use PhoenixHTMLHelpers` will import all of its submodules (as `use Phoenix.HTML` does)
* [x] `use Phoenix.HTML` will raise telling people to install the new dependency and do `import Phoenix.HTML; use PhoenixHTMLHelpers` - this is literally all that is needed to update

To release, we will need:

* [x] Ship `phoenix_view` with an additional `or ~> 4.0` requirement
* [x] Ship `phoenix_ecto` with an additional `or ~> 4.0` requirement
* [x] Ship `phoenix_live_dashboard` with an additional `or ~> 4.0` requirement
* [x] Ship `phoenix_live_view` with an additional `or ~> 4.0` requirement
* [x] Ship `phoenix_html_helpers`
* [x] Ship `phoenix_html` v4.0.0

Note the migration above will only be required for Phoenix apps before v1.7. v1.7 only does `import Phoenix.HTML` and the APIs used in `core_components` will remain part of this project, so the migration is only a dependency bump.

**Comment by josevalim** [comment]
@sorentwo you will want to add `{:phoenix_html, github: "phoenixframework/phoenix_html", override: true}` to ObanWeb and make sure it works. You most likely don't depend on Phoenix.HTML directly, which means that ObanWeb may fail in new apps. Check latest commits to Phoenix.LiveDashboard to see an example of how to migrate.

**Comment by sorentwo** [comment]
@josevalim Aye aye, thanks for the tip!

**Comment by sorentwo** [comment]
There's a transitive error from LV:

```
** (UndefinedFunctionError) function Phoenix.HTML.Tag.content_tag/3 is undefined (module Phoenix.HTML.Tag is not available)
```

Which I see is [fixed in phoenix_live_view main](https://github.com/phoenixframework/phoenix_live_view/commit/3fae55efc791d39ccd9411b09810ff0138a60452). I'll have to revisit this once a new LV version is released.

**Comment by josevalim** [comment]
Yes, I used LV from GitHub when testing too. :)

**Comment by josevalim** [comment]
v4.0.0 is out!
