### ISSUE TITLE
No 3.3.0 JavaScript release on NPM

### ISSUE THREAD

**Issue by s3cur3** [phoenixframework/phoenix_html#406]
Hi there! First, let me say thanks for all the work that went into 3.3.0. It's a huge force multiplier for our team. (I'm especially excited about the `Phoenix.HTML.Safe` implementation for `URI`. 😄)

Could we get an NPM release of version 3.3.0? Despite the availability of the `.js` files in our Elixir deps, our React-based frontend team prefers to get the JavaScript files from NPM.

**Comment by josevalim** [comment]
done!

**Comment by s3cur3** [comment]
Thank you! 🥂
