### ISSUE TITLE
Submit button genereted in v3.3.0 is not hidden

### ISSUE THREAD

**Issue by Fubuchi** [phoenixframework/phoenix_html#413]
I am following the phoenix book but using phoenix 1.6 instead.

At chapter 5, when implemented the logout function, I sent a delete request to clear the session. When I clicked the logout link, a submit button appeared at the bottom left of the page:

![image](https://user-images.githubusercontent.com/42483897/221435423-807951a7-4f4f-4f49-944f-646898fb00c8.png)

In v3.3, an input `<input type="submit">` is used to perform the request. After some discussion in the phoenix discord channel, we found out that the button can not be hidden if milligram css is loaded.

The button should be hidden as v3.2

Here is the link to the template of the image above: https://github.com/Fubuchi/rumbl/blob/master/lib/rumbl_web/templates/layout/root.html.heex#L26

**Comment by josevalim** [comment]
Thanks for the report. I pushed a fix, can you try it out? `{:phoenix_html, github: "phoenixframework", override: true}`

**Comment by Fubuchi** [comment]
Confirm the latest code fix the issue. The dep is `{:phoenix_html, github: "phoenixframework/phoenix_html", override: true}` though.

**Comment by josevalim** [comment]
thanks. 3.3.1 published.
