### ISSUE TITLE
Liveview push_patch not working starting from version 3.3.0

### ISSUE THREAD

**Issue by Szetty** [phoenixframework/phoenix_html#417]
Basically since we changed to this version (3.3.0) our [push_patch](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#push_redirect/2) has stopped working on JS side.

We are seeing this error on version 3.3.0:

![image](https://user-images.githubusercontent.com/9341214/223650189-43ddcfba-c012-4ca7-9830-8d80b04d855d.png)

And inspecting the value, it is indeed null:

![e55e7c49-f666-431f-9dff-d500a1ee5a0b](https://user-images.githubusercontent.com/9341214/223649539-cdda3b68-1804-4b88-a862-abc4b53db44d.jpg)

On version 3.2.0 we have this for the same value:

![2c068544-2768-4230-aa1f-c8150dd5d094](https://user-images.githubusercontent.com/9341214/223649831-407fe3ce-af8e-4cd2-a3b9-b0dbf61bbe55.jpg)

**Comment by Szetty** [comment]
Started to debug more, and found that the problem is here:
![image](https://user-images.githubusercontent.com/9341214/223655028-90064f45-ae7f-423e-a822-7b02401a07d3.png)

Basically `this.main = view` is not called for some reason. Although checking the rootEl I can see the attribute:

![image](https://user-images.githubusercontent.com/9341214/223656506-1d89f14b-6f62-4ccb-a037-60016cd6d1e5.png)

**Comment by josevalim** [comment]
What is your LiveView version? I am using 0.18.x and it definitely works here. You may need to update LiveView or keep using 3.2 until you can do so. :)

**Comment by Szetty** [comment]
Found the problem, it is related to this commit from what I understand: https://github.com/phoenixframework/phoenix_html/commit/4904ed1c5f0805c67d1e4ba11eb8603beaaf5745

Old version:

![image](https://user-images.githubusercontent.com/9341214/223660872-bbd301b7-f1fe-4fb2-aa37-4df20346ac00.png)

![image](https://user-images.githubusercontent.com/9341214/223661001-13322b13-ddad-41b4-b6db-243154b0a600.png)

![image](https://user-images.githubusercontent.com/9341214/223661195-65bf7c27-68ed-46b3-8e1d-7feca1980c97.png)

New version:

![image](https://user-images.githubusercontent.com/9341214/223661754-f1a8dd6e-5f83-4268-a1aa-e29e38921dde.png)

![image](https://user-images.githubusercontent.com/9341214/223661811-fcd52dc3-111c-4f30-b95a-510cb6feecd3.png)

![image](https://user-images.githubusercontent.com/9341214/223661901-1e56de02-4434-4b5d-8405-b057bb94acd0.png)

**Comment by Szetty** [comment]
> What is your LiveView version? I am using 0.18.x and it definitely works here. You may need to update LiveView or keep using 3.2 until you can do so. :)

![image](https://user-images.githubusercontent.com/9341214/223662311-3d2e3bd4-f38d-4d2d-98f8-cfc3badf7fa4.png)

**Comment by Szetty** [comment]
Thank you @josevalim, found the phoenix_live_view commit fixing this : https://github.com/phoenixframework/phoenix_live_view/commit/604d0f740df7d386bdeb055d6194494e0ed5e558

**Comment by Szetty** [comment]
For further help in order to run `phoenix_html > 3.3.0` you need `phoenix_live_view > 0.18.4`.

**Comment by Sleepful** [comment]
Had a similar issue. Updating the deps wasn't enough to fix it, but after running these commands it worked fine:

```
cd assets
rm -rf node_modules
npm i
cd ../
rm -rf _build
mix compile
mix phx.server
```
