### ISSUE TITLE
Inserting into DB from form hangs server for multiple seconds

### ISSUE THREAD

**Issue by leifertin** [phoenixframework/phoenix_html#421]
Starting with version 3.3.0

**Comment by josevalim** [comment]
Please provide a mechanism to reproduce the issue. I use the same version and I haven’t seen any issues.

**Comment by leifertin** [comment]
It seems to happen when I use `push_redirect` after create. When I switch to `redirect` it is fine.

https://user-images.githubusercontent.com/7034305/236567958-dc037d19-ef53-4823-8d69-7bb33ef4ec92.mov

**Comment by josevalim** [comment]
We still need a way to reproduce it, thanks. Also check your browser console for hints.

**Comment by leifertin** [comment]
I will try more to reproduce it before opening an issue next time. Thank you :)
