### ISSUE TITLE
Cant install 4.0.0

### ISSUE THREAD

**Issue by atomkirk** [phoenixframework/phoenix_html#437]
I might be doing something wrong or this is unrelated, but I haven't see it before, only with this package.

I change
```elixir
{:phoenix_html, "~> 3.3.2"},
```
to
```elixir
{:phoenix_html, "~> 4.0.0"},
```
and do
```bash
mix deps.unlock phoenix_html
mix deps.get
```
and I get
```bash
Resolving Hex dependencies...
Resolution completed in 0.021s
Because your app depends on phoenix_html empty which doesn't match any versions, version solving failed.
** (Mix) Hex dependency resolution failed
```

Any idea whats up?

**Comment by josevalim** [comment]
This is a Hex bug: https://github.com/hexpm/hex/issues/972

It means you have a path or a git dependency that conflicts with phoenix_html. If you address that, you should be good to go!

**Comment by josevalim** [comment]
PS: hex has a fix for it, but it was not released yet because it introduced a regression :)

**Comment by atomkirk** [comment]
What happened to hidden_inputs_for? my deps depended on it.

**Comment by josevalim** [comment]
@atomkirk you can add this to your markup instead:

        <input :for={{name, value} <- form.hidden} type="hidden" name={name} value={value} />

**Comment by atomkirk** [comment]
thanks
