### ISSUE TITLE
Add value_from to the public form API

### ISSUE THREAD

**Issue by sumerman** [phoenixframework/phoenix_html#44]
Every time I need to do something custom I had to use undocumented ways of getting the value out of the form parameter. It feels especially scary when working with nested forms. BTW exposing id and name will be also helpful.

**Comment by bryansray** [comment]
> Every time I need to do something custom

@sumerman don't suppose you could elaborate a bit more? Could you provide a use case for your something custom?

> BTW exposing id and name will be also helpful

I'm not sure I see the benefit of exposing the id and name? I'm assuming you mean this on the actual input fields of the form_for? Could you describe a use case for this too?

**Comment by sumerman** [comment]
1) select item which has to show values from a has_one relation (not showing them currently)
2) label which have to show value (currently disabled text input is used)

**Comment by josevalim** [comment]
> Every time I need to do something custom I had to use undocumented ways of getting the value out of the form parameter.

Those ways are not undocumented. The form data is documented and public, you can access its fields directly, as we do in our helpers.

**Comment by sumerman** [comment]
@josevalim is there any documented way to generate proper ids and names for custom controls that will be properly picked up by nested forms?

**Comment by josevalim** [comment]
@sumerman you can implement it exactly as in those functions, just concat them. You don't need to change anything for them to work with nested forms. :)

**Comment by josevalim** [comment]
To be clear, I don't mind making those functions public but, if we do, we need better names. field_value, field_id and field_name maybe?

**Comment by sumerman** [comment]
@josevalim and then something changes on the `phoenix_html` side ;) In my opinion it's too fragile to rely on the undocumented naming convention.

**Comment by josevalim** [comment]
If it changes it would be 3.0. Then there is no guarantee the functions we provide would still be there as well.

**Comment by sumerman** [comment]
@josevalim nevertheless, I feel more comfortable when breaking changes break my build, not just the rendering of some pages sometimes.

**Comment by josevalim** [comment]
In any case, can you please provide a PR that exports value_from, name_from and id_from as field_value, field_name and field_id with docs and tests? I will gladly merge it :)
