### ISSUE TITLE
Phoenix.HTML.Form uses params instead of changeset value

### ISSUE THREAD

**Issue by cjbottaro** [phoenixframework/phoenix_html#446]
Here is some dbg() output.

```elixir
f[:current] #=> %Phoenix.HTML.FormField{
  form: %Phoenix.HTML.Form{
    params: %{
      "current" => "false",
      "end_on" => "",
      "name" => "Fall 2024 ",
      "quick_filter" => "",
      "start_on" => "06/05/2024"
    }
  }
  value: "false"
}

f[:current].form.source #=> #Ecto.Changeset<
  action: :validate,
  changes: %{name: "Fall 2024 "},
  errors: [],
  data: #AwardCycle<>,
  valid?: true
>
|> Ecto.Changeset.get_field(:current) #=> true
```

Notice that `form[:current].value` is `"false"` rather than what the changeset says the field is.

The use case here is a disabled checkbox. We want to render the checkbox as disabled/readonly. On the initial page render, it correctly renders as checked and disabled. But any kind of `phx-change` event that triggers validation will cause it to become unchecked.

Our changeset doesn't cast the field at all...
```elixir
thing = AwardCycle.find(123)
changeset = Ecto.Changeset.cast(thing, params, [:name])
Ecto.Changeset.get_change(changeset, :current) # nil
Ecto.Changeset.get_field(changeset, :current) # true
```

Shouldn't `form[key].value` be using `Ecto.Changeset.get_field(form.source, key)` instead of `params[key]`?

Thanks for the help!

**Comment by josevalim** [comment]
Params always wins, because you want to return what the user has precisely submitted. For example, if the user gives an invalid date, you want to render that in the input back to the user, rather than rolling back to the original value and forcing the user to type it all again. It has worked like this for several years. :)

**Comment by cjbottaro** [comment]
Yeah, that makes total sense, not sure why I thought otherwise... 😂 

In this use case of the disabled checkbox, it's easy enough to just make a second hidden input:
```elixir
<.input label="Current" field={f[:current]} type="checkbox" disabled={@award_cycle.current} />
<%= if @award_cycle.current do %>
  <.input field={f[:current]} type="hidden" value="true" />
<% end %>
```

👍
