### ISSUE TITLE
& and co. in URLs should not be escaped

### ISSUE THREAD

**Issue by ruslandoga** [phoenixframework/phoenix_html#454]
👋 

It seems like Phoenix.HTML unnecessarily escapes query strings on the first, "dead" render.

```elixir
qs = %{a: :b, c: :d}
assigns = assign(assigns, path: ~p"/?#{qs}")

~H"""
<.link patch={@path}>...</.link>
"""
```

results in

```html
<a href="/?a=b&amp;c=d">...</a>
```

which gets parsed by Plug into 

```elixir
iex> Plug.Conn.Query.decode "a=b&amp;c=d"
#==> %{"a" => "b", "amp;c" => "d"}
```

**Comment by ruslandoga** [comment]
Repro: https://github.com/ruslandoga/amp/commit/834cb4ab671ea1b3d5e182f053a229f78b643ab1

The test fails with

```
  1) test example (AmpWeb.PageControllerTest)
     test/amp_web/controllers/page_controller_test.exs:10
     Assertion with == failed
     code:  assert Phoenix.LiveViewTest.render_component(&AmpWeb.CoreComponents.example/1, query: %{a: :b, c: :d}) ==
              "<a href=\"/?c=d&a=b\" data-phx-link=\"patch\" data-phx-link-state=\"push\">example</a>"
     left:  "<a href=\"/?c=d&amp;a=b\" data-phx-link=\"patch\" data-phx-link-state=\"push\">example</a>"
     right: "<a href=\"/?c=d&a=b\" data-phx-link=\"patch\" data-phx-link-state=\"push\">example</a>"
     stacktrace:
       test/amp_web/controllers/page_controller_test.exs:11: (test)
```

**Comment by josevalim** [comment]
We need to escape those otherwise someone can unquote and inject any HTML content, no? The browser should be unescaping those and doing the correct request?

**Comment by ruslandoga** [comment]
Ah, right. Safari unescapes it, and Floki does too:

```elixir
iex> Floki.parse_fragment("<a href=\"/?a=b&amp;c=d\">hello</a>")
#==> {:ok, [{"a", [{"href", "/?a=b&c=d"}], ["hello"]}]}
```

**Comment by SteffenDE** [comment]
@ruslandoga btw if you give ChatGPT enough context, you'll also get a better answer:

Original Chat (seems it's gone now?):

> should any of these be escaped in URL query strings?
>
>  escapes = [
>    {?<, "&lt;"},
>    {?>, "&gt;"},
>    {?&, "&amp;"},
>    {?", "&quot;"},
>    {?', "&#39;"}
>  ]

> No, the characters in your list (<, >, &, ", ') do not need to be escaped in URL query strings specifically. They are instead typically escaped in HTML or other contexts where content is displayed in a browser to prevent injection attacks or rendering issues.
> ...

Now we give it more context in a followup question:

> What if the URL is rendered in an HTML link attribute?

> If the URL is rendered in an HTML link attribute (such as in an anchor <a> tag's href attribute), then yes, characters like <, >, &, ", and ' should be escaped to ensure proper HTML rendering and prevent injection issues, such as XSS (Cross-Site Scripting).

While you theoretically can do a little less escaping (the & could be left unescaped if it's not an "ambiguous ampersand"), it is simpler and also not wrong to just always escape these. See also https://stackoverflow.com/questions/41596274/what-characters-must-be-escaped-in-html5-attributes

> I wonder if email clients are as smart. I'll try it tomorrow.

If they render HTML I would assume so :)

**Comment by SteffenDE** [comment]
![image](https://github.com/user-attachments/assets/64648b38-4d6a-464a-b276-bd153ae80bfd)

Weird.

> I am particularly interested in non-HTML emails, and the clients that turn what looks like links there into links.

I think if you don't render HTML emails, you shouldn't use HEEx as it is meant for handling HTML. So yeah, as you said:

> Phoenix.HTML being used "incorrectly" outside of Phoenix projects

Although I'd say "outside of an HTML context" as you can absolutely use Phoenix.HTML without Phoenix :)

In that case I'd suggest to instead use regular EEx templates. In there, you'd then use `URI.encode_query` like you did.

**Comment by ruslandoga** [comment]
> Although I'd say "outside of an HTML context" as you can absolutely use Phoenix.HTML without Phoenix :)

That's not what I meant :) What I meant was that if HEEx escapes URLs correctly other users of Phoenix.HTML might not.
