### ISSUE TITLE
Hexdocs link is broken

### ISSUE THREAD

**Issue by houshuang** [phoenixframework/phoenix_html#5]
https://hexdocs.pm/phoenix_html/ returns page not found

**Comment by josevalim** [comment]
@ericmj can they be disappearing? I haven't pushed anything since we fixed this...

**Comment by ericmj** [comment]
They seem to be, but I have no idea why, there only seems to be issues with phoenix_html. I haven't got reports about any other package docs going missing, I will investigate.

**Comment by ericmj** [comment]
Fixed the bug.
