### ISSUE TITLE
Allow translations to be passed as arguments

### ISSUE THREAD

**Issue by kaisersly** [phoenixframework/phoenix_html#51]
Currently months are hard-coded. It would be great if we were able to pass an array with months in other languages.

**Comment by chrismccord** [comment]
You can pass a list of options in today, i.e.:

```elixir
date_select form, :datetime, month: [options: [{"Jan", 1}, {"Feb", 2}]],
                             year: [options: 2000..2020]
```

**Comment by josevalim** [comment]
Let's leave this open because we should consider if we will support gettext out of the box.

**Comment by chrismccord** [comment]
@josevalim agree. I am tinkering locally

**Comment by josevalim** [comment]
@chrismccord let's not worry about it *now*. I would like to wait for more use cases. But let's leave it open as a reminder.

**Comment by kaisersly** [comment]
Ok thanks for the tip. Gettext is a good idea as well.

**Comment by apeacox** [comment]
@chrismccord  @josevalim Any updates on this issue? I was wondering the same thing about supporting gettext. I have the same problem with months in `date_select`. Yes, I could pass options manually but having built-in support for gettext would be great.

**Comment by josevalim** [comment]
@apeacox any ideas on how we could implement this? In any case we would need to pass the gettext backend, either to the form or to the helper. I believe to the form would be better?

**Comment by apeacox** [comment]
Well, I think it would be better to add this inside the helper (eg: calling `gettext("January")` in `@months` annotation?)

On a side note, I didn't investigate (yet) on how it was implemented for Ecto's errors messages, perhaps it's possible to follow a similar approach?

**Comment by josevalim** [comment]
@apeacox we can't call it when compiling phoenix_html because the gettext module likely was not compiled yet since it belongs to the parent project.

**Comment by apeacox** [comment]
Ouch! You're right :-P

For now, I've solved with a custom module to import inside the views, then I use it as month's options for `date_select`.

Here's the code for reference:

```
defmodule MyApp.ViewHelpers do
  @moduledoc """
  This module defines some view helpers.
  """

  import MyApp.Gettext

  @doc """
  Generates month date_select/datetime_select options wrapped in a gettext call.
  """
  def gettext_month_options do
    [
      {gettext("January"), 1},
      {gettext("February"), 2},
      {gettext("March"), 3},
      {gettext("April"), 4},
      {gettext("May"), 5},
      {gettext("June"), 6},
      {gettext("July"), 7},
      {gettext("August"), 8},
      {gettext("September"), 9},
      {gettext("October"), 10},
      {gettext("November"), 11},
      {gettext("December"), 12},
    ]
  end
end
```

**Comment by michalmuskala** [comment]
I think it's the way to do it. You could even unimport the phoenix-provided `date_select` helper and replace with your own that would use those by default.

The question is - should phoenix generator provide something like this, by default?

**Comment by apeacox** [comment]
Some kind of generator would be very useful, I was also thinking to release a separate package, something like this:

https://github.com/tuvistavie/phoenix-active-link

**Comment by josevalim** [comment]
I believe this should be part of Phoenix per se. Specially if we want to have a more complete I18n story.
