### ISSUE TITLE
Should iodata be char data?

### ISSUE THREAD

**Issue by henrik** [phoenixframework/phoenix_html#53]
I'm writing a blog post about char data, and looked into what Phoenix.HTML did in that respect.

I see the code deals with iodata – might char data be a better idea? As I understand it, the difference is that iodata treats integers as raw bytes and char data treats them as UTF-8 codepoints.

**Comment by henrik** [comment]
I finished that blog post. It has an example of the IO data/char data difference, though I suspect you have a better grasp of it than I do. http://thepugautomatic.com/2015/12/char-data/

**Comment by henrik** [comment]
Reading up further, I see that `IO.iodata_to_binary/1` is supposedly inlined by the compiler. I guess the Unicode-aware versions are not. So maybe this is an optimization. Could make sense since Phoenix.HTML is likely to deal in binaries and not raw byte values.

**Comment by josevalim** [comment]
It doesn't matter much because you are supposed to be using lists. so for performance sake, it is better to use iodata as that's how we will send it down the socket. :)
