### ISSUE TITLE
Stylesheet and Script tags

### ISSUE THREAD

**Issue by nettofarah** [phoenixframework/phoenix_html#55]
Would it make sense to have a couple of helper functions for `script` and `style` tags?

So this sort of code
```eex
 <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
```
could be written like this:
```eex
<%= script_tag(static_path(@conn, "/js/app.js")) %>
```

or maybe we go even crazier and do something like:
```eex
<%= asset_tag(@conn, "/js/app.js") %>
```
And figure out what sort of tag we need to include (maybe a little too magical?).

**Comment by nettofarah** [comment]
I would love to implement this if y'all think it makes sense to build it.

**Comment by chrismccord** [comment]
We have `content_tag`, which will let you do:

    <%= content_tag :script, src: static_path(@conn, "/js/apps.js") %>

I may double back on this, but for now I'd prefer to leave this out and add later if it becomes obvious we need them. Thanks!

**Comment by nettofarah** [comment]
Sounds good! Thanks!
