### ISSUE TITLE
where is error_tag?

### ISSUE THREAD

**Issue by austinsmorris** [phoenixframework/phoenix_html#56]
`phoenix.gen.html.ex` has this:

```
  defp error(field) do
    ~s(<%= error_tag f, #{inspect(field)} %>)
  end
```

But Phoenix.HTML doesn't seem to define an `error_tag` function, resulting in a compilation error:

`** (CompileError) web/templates/video/form.html.eex:11: function error_tag/2 undefined`

**Comment by josevalim** [comment]
It should be part of your application. Please check the upgrade instructions: https://gist.github.com/chrismccord/557ef22e2a03a7992624

**Comment by austinsmorris** [comment]
Fantastic!  I must have missed that between updates for my Rumbl application :smile:.  Thanks, and happy holidays!
