### ISSUE TITLE
Incorrect dialyzer type mismatch

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix_html#64]
A newly installed phoenix 1.1.4 app has a problem with html.eex functions

```
index.html.eex:1: The pattern {'safe', _@2} can never match the type binary()
```

I've created a [phoenix app](https://github.com/paulcsmith/dialyze-demo) that you can clone and run `mix do compile, dialyzer.plt, dialyzer` and see the output. This is related to https://github.com/elixir-lang/elixir/issues/4240#issuecomment-176878659 which contains a bit more information about the problem for those that are curious :)

I would open a PR, but I'm still not entirely sure how to mark a clause as generated :S I'd be happy to help if you could provide some guidance, but I'm also ok if you it's easier to just fix by yourself. LMK if you need any other info!

**Comment by paulcsmith** [comment]
I attempted to figure this one out and couldn't quite get it where to mark the code as generated. I think it might be better if someone else tackled this one :S

**Comment by josevalim** [comment]
No problem @paulcsmith! :D

**Comment by tmjoen** [comment]
@paulcsmith looks like there is support coming in Elixir 1.3 for marking as generated: https://github.com/elixir-lang/elixir/commit/8b6145d8f957f9996845bfc4a5ede7d94d93f0ac

I tried manually adding [generated: true] to the quoted expression's meta, but I couldn't make it work and I'm way out of my depth here 💫

**Comment by mcherep** [comment]
I still have this issue with Phoenix 1.3 and Elixir 1.3.4. Is this going to be fixed in Phoenix, or it has to be fixed manually in every project?

**Comment by josevalim** [comment]
Closing this as we are now marking entries as generated.
