### ISSUE TITLE
Match error in normalize_form

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_html#65]
This was just reported by a user, and locking phoenix_html to 2.4.0 was a temporary fix. I will investigate later, but leaving here as a reference:

```
Request: GET /users/new
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.normalize_form/1
        (phoenix_html) lib/phoenix_html/form.ex:239: Phoenix.HTML.Form.normalize_form(%{__struct__: Phoenix.HTML.Form, errors: [], hidden: [], id: "user", impl: Phoenix.HTML.FormData.Ecto.Changeset, index: nil, model: %Rumbl.User{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil, name: nil, password: nil, password_hash: nil, updated_at: nil, username: nil, videos: #Ecto.Association.NotLoaded<association :videos is not loaded>}, name: "user", options: [method: "post"], params: %{}, source: %Ecto.Changeset{action: nil, changes: %{}, constraints: [], errors: [], filters: %{}, model: %Rumbl.User{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil, name: nil, password: nil, password_hash: nil, updated_at: nil, username: nil, videos: #Ecto.Association.NotLoaded<association :videos is not loaded>}, optional: [], opts: [], params: nil, prepare: [], repo: nil, required: [:name, :username], types: %{id: :id, inserted_at: Ecto.DateTime, name: :string, password: :string, password_hash: :string, updated_at: Ecto.DateTime, username: :string, videos: {:assoc, %Ecto.Association.Has{cardinality: :many, defaults: [], field: :videos, on_cast: :changeset, on_delete: :nothing, on_replace: :raise, owner: Rumbl.User, owner_key: :id, queryable: Rumbl.Video, related: Rumbl.Video, related_key: :user_id}}}, valid?: false, validations: [username: {:length, [min: 1, max: 20]}]}})
        (phoenix_html) lib/phoenix_html/form.ex:234: Phoenix.HTML.Form.form_for/4
        (rumbl) web/templates/user/new.html.eex:9: Rumbl.UserView."new.html"/1
        (rumbl) web/templates/layout/app.html.eex:36: Rumbl.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.action/2
        (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.phoenix_controller_pipeline/2
        (rumbl) lib/phoenix/router.ex:261: Rumbl.Router.dispatch/2
        (rumbl) web/router.ex:1: Rumbl.Router.do_call/2
        (rumbl) lib/rumbl/endpoint.ex:1: Rumbl.Endpoint.phoenix_pipeline/1
        (rumbl) lib/plug/debugger.ex:93: Rumbl.Endpoint."call (overridable 3)"/2
        (rumbl) lib/phoenix/endpoint/render_errors.ex:34: Rumbl.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by josevalim** [comment]
It is a bug in Elixir. We were not recompiling phoenix_ecto. Mix deps.clean
phoenix_ecto should fix it.

On Saturday, January 30, 2016, Chris McCord <notifications@github.com>
wrote:

> This was just reported by a user, and locking phoenix_html to 2.4.0 was a
> temporary fix. I will investigate later, but leaving here as a reference:
>
> Request: GET /users/new
> ** (exit) an exception was raised:
>     ** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.normalize_form/1
>         (phoenix_html) lib/phoenix_html/form.ex:239: Phoenix.HTML.Form.normalize_form(%{__struct__: Phoenix.HTML.Form, errors: [], hidden: [], id: "user", impl: Phoenix.HTML.FormData.Ecto.Changeset, index: nil, model: %Rumbl.User{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil, name: nil, password: nil, password_hash: nil, updated_at: nil, username: nil, videos: #Ecto.Association.NotLoaded<association :videos is not loaded>}, name: "user", options: [method: "post"], params: %{}, source: %Ecto.Changeset{action: nil, changes: %{}, constraints: [], errors: [], filters: %{}, model: %Rumbl.User{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil, name: nil, password: nil, password_hash: nil, updated_at: nil, username: nil, videos: #Ecto.Association.NotLoaded<association :videos is not loaded>}, optional: [], opts: [], params: nil, prepare: [], repo: nil, required: [:name, :username], types: %{id: :id, inserted_at: Ecto.DateTime, na
>  me: :string, password: :string, password_hash: :string, updated_at: Ecto.DateTime, username: :string, videos: {:assoc, %Ecto.Association.Has{cardinality: :many, defaults: [], field: :videos, on_cast: :changeset, on_delete: :nothing, on_replace: :raise, owner: Rumbl.User, owner_key: :id, queryable: Rumbl.Video, related: Rumbl.Video, related_key: :user_id}}}, valid?: false, validations: [username: {:length, [min: 1, max: 20]}]}})
>         (phoenix_html) lib/phoenix_html/form.ex:234: Phoenix.HTML.Form.form_for/4
>         (rumbl) web/templates/user/new.html.eex:9: Rumbl.UserView."new.html"/1
>         (rumbl) web/templates/layout/app.html.eex:36: Rumbl.LayoutView."app.html"/1
>         (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
>         (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
>         (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.action/2
>         (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.phoenix_controller_pipeline/2
>         (rumbl) lib/phoenix/router.ex:261: Rumbl.Router.dispatch/2
>         (rumbl) web/router.ex:1: Rumbl.Router.do_call/2
>         (rumbl) lib/rumbl/endpoint.ex:1: Rumbl.Endpoint.phoenix_pipeline/1
>         (rumbl) lib/plug/debugger.ex:93: Rumbl.Endpoint."call (overridable 3)"/2
>         (rumbl) lib/phoenix/endpoint/render_errors.ex:34: Rumbl.Endpoint.call/2
>         (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
>         (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix_html/issues/65>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
Ah, then all we need to do is at that step to the Phoenix upgrade guides and we're set. Thanks!
