### ISSUE TITLE
debris in textarea

### ISSUE THREAD

**Issue by KozakIvan** [phoenixframework/phoenix_html#67]
Create new project and add <%= tag(:textarea, name: "text") %> in page.html.ex template

Result:
textarea contains debris of html page

**Comment by josevalim** [comment]
You need to use content tag otherwise the textarea won't be closed.

On Thursday, February 4, 2016, Kozak Ivan <notifications@github.com> wrote:

> Create new project and add <%= tag(:textarea, name: "text") %> in
> pagehtmlex template
>
> Result:
> textarea contains debris of html page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix_html/issues/67>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by KozakIvan** [comment]
@josevalim ups, my bad, thanks
