### ISSUE TITLE
inputs_for with file_input raises even when form_for contains multipart: true

### ISSUE THREAD

**Issue by RoelWKramer** [phoenixframework/phoenix_html#70]
Imagine a photo album where an Album has_many pictures and a Picture belongs_to Album. If I want to create an album and add a few pictures, I should be able to use inputs_for/4. It does not work though. When using the code below, an error is raised:

>  file_input/3 requires the enclosing form_for/4 to be configured with multipart: true

```
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= text_input f, :album_title, value: "my title", class: "form-control" %>

  <%= inputs_for f, :pictures, fn fp -> %>
    <%= file_input fp, :file,  class: "form-control" %>
  <% end %>
<% end %>
```

The unittests of phoenix_html do not test this. This line (https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L495) checks if form has multipart: true, but when using inputs_for, the parent form map is probably not passed. The inputs_for tests do not contain any file_field specific tests.

**Comment by josevalim** [comment]
Great catch.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by RoelWKramer** [comment]
It does work though if i do:
<%= inputs_for f, :pictures, [multipart: true], fn fp -> %>
