### ISSUE TITLE
Use event delegation in phoenix_html.js

### ISSUE THREAD

**Issue by maufl** [phoenixframework/phoenix_html#75]
Currently, one event handler is attached to each element that uses `data-submit=parent`.
The downside is that  the elements must be present in the DOM when the file is loaded. I think that also means that the script tag with the code **must** come after the elements.

Instead we could use [event delegation](https://davidwalsh.name/event-delegate). The event handler can then be attached to the body and will work for any element, whenever it is loaded in the DOM (via Ajax for example).

**Comment by chrismccord** [comment]
Would you like to send a PR?

**Comment by maufl** [comment]
Yes, I'll probably do that soon. I don't have time today and the issue is not that pressing, I just wanted it have it documented here.

**Comment by josevalim** [comment]
Beautiful, thank you!
