### ISSUE TITLE
Missing v2.5.1 tag on GitHub

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_html#81]
Not a huge deal, but because the tag is missing docs can't link to the source:
- https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#checkbox/3
- https://github.com/phoenixframework/phoenix_html/blob/v2.5.1/lib/phoenix_html/form.ex#L624

**Comment by josevalim** [comment]
Done!
