### ISSUE TITLE
Phoenix.HTML.Form.form_for/4 is not working with Changeset

### ISSUE THREAD

**Issue by eniolopes** [phoenixframework/phoenix_html#85]
According to the documentation [here](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html), `form_for/4 receives the Ecto.Changeset and converts it to a form, which is passed to the function as the argument f.`

I'm following the Programming Phoenix book building the Rumbl application, when rendering the user form I'm getting the following error:
```
[error] #PID<0.372.0> running Rumbl.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /users/new
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.HTML.FormData not implemented for %Ecto.Changeset{action: nil, changes: %{}, constraints: [], errors: [], filters: %{}, model: %Rumbl.User{__meta__: #Ecto.Schema.Metadata<:built>, id: nil, inserted_at: nil, name: nil, password: nil, password_hash: nil, updated_at: nil, username: nil}, optional: [], opts: [], params: nil, prepare: [], repo: nil, required: [:name, :username], types: %{id: :id, inserted_at: Ecto.DateTime, name: :string, password: :string, password_hash: :string, updated_at: Ecto.DateTime, username: :string}, valid?: false, validations: [username: {:length, [min: 1, max: 20]}]}
        (phoenix_html) lib/phoenix_html/form_data.ex:1: Phoenix.HTML.FormData.impl_for!/1
        (phoenix_html) lib/phoenix_html/form_data.ex:15: Phoenix.HTML.FormData.to_form/2
        (phoenix_html) lib/phoenix_html/form.ex:234: Phoenix.HTML.Form.form_for/4
        (rumbl) web/templates/user/new.html.eex:2: Rumbl.UserView."new.html"/1
        (rumbl) web/templates/layout/app.html.eex:29: Rumbl.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.action/2
        (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.phoenix_controller_pipeline/2
        (rumbl) lib/phoenix/router.ex:261: Rumbl.Router.dispatch/2
        (rumbl) web/router.ex:1: Rumbl.Router.do_call/2
        (rumbl) lib/rumbl/endpoint.ex:1: Rumbl.Endpoint.phoenix_pipeline/1
        (rumbl) lib/plug/debugger.ex:93: Rumbl.Endpoint."call (overridable 3)"/2
        (rumbl) lib/phoenix/endpoint/render_errors.ex:34: Rumbl.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Not sure what I'm missing, I don't see a `defimpl` for `Ecto.Changeset` on [Phoenix.HTML.FormData](https://github.com/phoenixframework/phoenix_html/blob/1341ba63bc63b897e833d63608574af8b7db2bae/lib/phoenix_html/form_data.ex)

I'm using Elixir 1.2.5 with Phoenix 1.1.5.

I'm probably missing something really simple.

**Comment by michalmuskala** [comment]
The `phoenix_ecto` package contains protocol definitions for ecto. Do you include it?

**Comment by eniolopes** [comment]
Yes.
```
* phoenix_ecto 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (phoenix_ecto) 1aff51d1
  ok
```

**Comment by eniolopes** [comment]
@michalmuskala I don't see it being included in `web/web.ex` should it be?

**Comment by eniolopes** [comment]
@josevalim It did, no idea why.

**Comment by josevalim** [comment]
We have improved such checks in Elixir v1.3.0 so, after you update, please let us know if it happens again!

**Comment by eniolopes** [comment]
Awesome! Thanks for the fast response. :)

**Comment by satb** [comment]
I ran into this same issue. Had no idea why it was happening until I stumbled into this issue...cleaned the _build and recompiled and everything was good again. Using elixir 1.3.4, ecto 2.0.6 and phoenix 1.2

**Comment by pdelanauze** [comment]
Elixir v1.4.2 , phoenix 1.2.4, ran into the same issue, clearing out _build fixed it !

**Comment by 7stud** [comment]
phoenix 1.4.0
elixir 1.6.6
phoenix_ecto 4.0.0  (dep: ecto 3.1.4)

I'm following along with the ebook Phoenix in Action (final edition), which creates an umbrella app, and on p. 168 the book implements the ```new``` action in the AuctionWeb.ItemController.  The corresponding template, ```new.html.eex```, employs the ```form_for()``` helper, which takes a changeset as the first argument, but I got the same blasted error mentioned here.  I checked my code carefully for mistakes, but I couldn't solve the issue.  I found this issue, and I did `rm -rf auction_umbrella/_build`, then I did ```.../auction_umbrella$ mix phx.server```, which recompiled all the files, and problem solved.

**Comment by raymondsiu** [comment]
I had the same issue following with the Phoenix in Action book. Having the phoenix_ecto package and cleaning up the _build folder solved the issue for me.
In my case I didn't build an umbrella app so my Phoenix layer is separate from my Model and separate from my User/Auth layer.

**Comment by shanlalit** [comment]
I generate the app with --no-ecto
So I needed {:phoenix_ecto, "~> 4.0"} dependency

**Comment by mikebobadilla** [comment]
removing _build and compiling again worked for me.

**Comment by Jbur43** [comment]
I was passing an empty struct of my context instead of a changeset. I needed to change my code so that I was actually casting the params and generating the changeset it was expecting
