### ISSUE TITLE
Do not hardcode class names

### ISSUE THREAD

**Issue by andrejsm** [phoenixframework/phoenix_html#86]
Please do not hardcode class names as found here
https://github.com/phoenixframework/phoenix_html/blob/v2.5.1/lib/phoenix_html/link.ex#L86
https://github.com/phoenixframework/phoenix_html/blob/v2.5.1/lib/phoenix_html/link.ex#L139

as it limits usage of selectors like `.link` and `.button`.
I would prefer to explicitly pass `:class` opt if one needed.

**Comment by michalmuskala** [comment]
As you can see a little bit below, it's only the default class if you don't provide your own:

https://github.com/phoenixframework/phoenix_html/blob/v2.5.1/lib/phoenix_html/link.ex#L160

So if you're not comfortable with the default class you are free to pass `form: [class: "my_awesome_class"]` or even `class: nil`.

This bahaviour could be better documented, though.

**Comment by josevalim** [comment]
PR for docs are always welcome. :)

**Comment by andrejsm** [comment]
Yes. I'm passing `nil` already. But I prefer explicit definition over defining `nil` to disable class addition.
Anyways, it's just me 😃

**Comment by michalmuskala** [comment]
You can define your own function with your own defaults really easily.

In the `web/web.ex`:
```elixir
def view do
  quote do
    # ...
    use Phoenix.HTML
    import Phoenix.HTML.Form, except: [link: 1, link: 2]
    import MyApp.HTML 
  end
end

# ...

defmodule MyApp.HTML do
  def link(opts, do: contents) when is_list(opts) do
    link(contents, opts)
  end

  def link(text, opts) do
    opts = update_in(opts[:form], &Keyword.put_new(&1 || [], :class, nil))
    Phoenix.HTML.Form.link(text, opts)
  end
end
```

And now you don't have the class in the whole app.

**Comment by andrejsm** [comment]
I'm fine with it. Just feeling it's not right to hardcode such a things.<div>
</div><div>
</div><div>-------- Sākotnējā ziņa --------</div><div>No: Michał Muskała <notifications@github.com> </div><div>Datums: 03.06.16  18:04  (GMT+02:00) </div><div>Kam: phoenixframework/phoenix_html <phoenix_html@noreply.github.com> </div><div>Kopija: Andrejs M <andrejs@ouk.lv>, Author <author@noreply.github.com> </div><div>Tēma: Re: [phoenixframework/phoenix_html] Do not hardcode class names (#86) </div><div>
</div>
You can define your own function with your own defaults really easily.

In the `web/web.ex`:
```elixir
def view do
  quote do
    # ...
    use Phoenix.HTML
    import Phoenix.HTML.Form, except: [link: 1, link: 2]
    import MyApp.HTML
  end
end

# ...

defmodule MyApp.HTML do
  def link(opts, do: contents) when is_list(opts) do
    link(contents, opts)
  end

  def link(text, opts) do
    opts = update_in(opts[:form], &Keyword.put_new(&1 || [], :class, nil))
    Phoenix.HTML.Form.link(text, opts)
  end
end
```

And now you don't have the class in the whole app.

---
