### ISSUE TITLE
could not compile dependency :phoenix_html, "mix compile" failed.

### ISSUE THREAD

**Issue by steve500002** [phoenixframework/phoenix_html#92]
I am trying to get an example Phoenix app running using the installation guide and I am getting an error with a newly installed app.

== Compilation error on file lib/phoenix_html/engine.ex ==
** (CompileError) lib/phoenix_html/engine.ex:77: unsupported option :generated given to quote

I am using Phoenix v1.2.0 and phoenix_html v 2.6.0

I have tried clearing the deps and starting again but I get back to the same place.

Getting phoenix_html (Hex package)
  Checking package (https://repo.hex.pm/tarballs/phoenix_html-2.6.0.tar)

Any ideas?

Thanks

Steve

**Comment by josevalim** [comment]
What is your Erland and Elixir versions?

On Sunday, June 26, 2016, Steve Brett <notifications@github.com> wrote:

> I am trying to get an example Phoenix app running using the installation
> guide and I am getting an error with a newly installed app.
>
> == Compilation error on file lib/phoenix_html/engine.ex ==
> ** (CompileError) lib/phoenix_html/engine.ex:77: unsupported option
> :generated given to quote
>
> I am using Phoenix v1.2.0 and phoenix_html v 2.6.0
>
> I have tried clearing the deps and starting again but I get back to the
> same place.
>
> Getting phoenix_html (Hex package)
> Checking package (https://repo.hex.pm/tarballs/phoenix_html-2.6.0.tar)
>
> Any ideas?
>
> Thanks
>
> Steve
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix_html/issues/92>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAAlbrmAeI6UX7iVSwXDs-r7icPxJKazks5qPbBqgaJpZM4I-cfu>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
It seems you are using Erlang 19 with an old Elixir version. You need to
either update Elixir to v1.2.6 or v1.3.0 or downgrade Erlang to version 18.

On Sunday, June 26, 2016, José Valim <jose.valim@plataformatec.com.br>
wrote:

> What is your Erland and Elixir versions?
>
> On Sunday, June 26, 2016, Steve Brett <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I am trying to get an example Phoenix app running using the installation
>> guide and I am getting an error with a newly installed app.
>>
>> == Compilation error on file lib/phoenix_html/engine.ex ==
>> ** (CompileError) lib/phoenix_html/engine.ex:77: unsupported option
>> :generated given to quote
>>
>> I am using Phoenix v1.2.0 and phoenix_html v 2.6.0
>>
>> I have tried clearing the deps and starting again but I get back to the
>> same place.
>>
>> Getting phoenix_html (Hex package)
>> Checking package (https://repo.hex.pm/tarballs/phoenix_html-2.6.0.tar)
>>
>> Any ideas?
>>
>> Thanks
>>
>> Steve
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/phoenixframework/phoenix_html/issues/92>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AAAlbrmAeI6UX7iVSwXDs-r7icPxJKazks5qPbBqgaJpZM4I-cfu>
>> .
>>
>
>
> --
>
>
> *José Valim*
> www.plataformatec.com.br
> Skype: jv.ptec
> Founder and Director of R&D
>
>

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by steve500002** [comment]
Thanks that solved my problem. I had not updated Homebrew so I was taking an old version of Elixir. 

Doh

Steve
