### ISSUE TITLE
Phoenix.HTML.Form.time_select generates "minute" param incompatible with Ecto.Time

### ISSUE THREAD

**Issue by rgreenjr** [phoenixframework/phoenix_html#93]
Not sure if I'm doing something wrong here, but after upgrading to Phoenix 1.2 I'm having trouble with forms containing `Ecto.Time` fields.

It looks like the form builder changed from using `min` to `minutes` and `Ecto.Time` is still expecting `min`.

For example, a simple post model:

```
defmodule Demo.Post do
  use Demo.Web, :model

  schema "posts" do
    field :publish_at, Ecto.Time

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:publish_at])
    |> validate_required([:publish_at])
  end
end
```

And form: 

```
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
      <%= label f, : publish_at, class: "control-label" %>
      <%= time_select f, :publish_at, class: "form-control" %>
      <%= error_tag f, :publish_at %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
```

Submits these params:

```
%{"_csrf_token" => "BzISPgNJJBJXZBNBJxUqMSIle3M4NgAAQtapj1st53GsvxnghWKAsw==",
  "_utf8" => "✓",
  "post" => %{"publish_at" => %{"hour" => "12", "minute" => "0"}}}
```

Calling `Repo.insert` on the resulting changeset generates an "is invalid" error on the `Ecto.Time` field.

```
#Ecto.Changeset<action: :insert, changes: %{title: "Demo"},
 errors: [publish_at: {"is invalid", [type: Ecto.Time]}], data: #Demo.Post<>,
 valid?: false>
``` 

The insert succeeds if I manually change `"%{"hour" => "12", "minute" => "0"}` to `%{"hour" => "12", "min" => "0"}`.

I hope this is enough info to be useful. Thanks.

**Comment by josevalim** [comment]
That's because of Elixir v1.3 new types. You can update to latest Ecto v1.1
or Ecto v2.0. Please let us know how it goes and your Ecto version in case
it still does not work.

On Monday, June 27, 2016, Ron Green <notifications@github.com> wrote:

> Not sure if I'm doing something wrong here, but after upgrading to Phoenix
> 1.2 I'm having trouble with forms containing Ecto.Time fields.
>
> It looks like the form builder changed from using min to minutes and
> Ecto.Time is still expecting min.
>
> For example, a simple post model:
>
> defmodule Demo.Post do
>   use Demo.Web, :model
>
>   schema "posts" do
>     field :publish_at, Ecto.Time
>
>     timestamps()
>   end
>
>   def changeset(struct, params \\ %{}) do
>     struct
>     |> cast(params, [:publish_at])
>     |> validate_required([:publish_at])
>   end
> end
>
> And form:
>
> <%= form_for @changeset, @action, fn f -> %>
>   <div class="form-group">
>       <%= label f, : publish_at, class: "control-label" %>
>       <%= time_select f, :publish_at, class: "form-control" %>
>       <%= error_tag f, :publish_at %>
>   </div>
>
>   <div class="form-group">
>     <%= submit "Submit", class: "btn btn-primary" %>
>   </div>
> <% end %>
>
> Submits these params:
>
> %{"_csrf_token" => "BzISPgNJJBJXZBNBJxUqMSIle3M4NgAAQtapj1st53GsvxnghWKAsw==",
>   "_utf8" => "✓",
>   "post" => %{"publish_at" => %{"hour" => "12", "minute" => "0"}}}
>
> Calling Repo.insert on the resulting changeset generates an "is invalid"
> error on the Ecto.Time field.
>
> #Ecto.Changeset<action: :insert, changes: %{title: "Demo"},
>  errors: [publish_at: {"is invalid", [type: Ecto.Time]}], data: #Demo.Post<>,
>  valid?: false>
>
> The insert succeeds if I manually change "%{"hour" => "12", "minute" =>
> "0"} to %{"hour" => "12", "min" => "0"}.
>
> I hope this is enough info to be useful. Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix_html/issues/93>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAAlbpHoEPOFcNqRXOh3GshASyXKKdOHks5qP-aTgaJpZM4I_MJT>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by rgreenjr** [comment]
I should have included my deps, which are all the latest I believe:

```
defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"}]
  end
```

**Comment by josevalim** [comment]
Those deps do not include the dependencies of your dependencies. "mix deps"
will show it. If you have Ecto v2.0.1 it should be good to go. Can you put
this application online on Github so I can investigate it too?

On Monday, June 27, 2016, Ron Green <notifications@github.com> wrote:

> I should have included my deps, which are all the latest I believe:
>
> defp deps do
>     [{:phoenix, "~> 1.2.0"},
>      {:phoenix_pubsub, "~> 1.0"},
>      {:phoenix_ecto, "~> 3.0"},
>      {:postgrex, ">= 0.0.0"},
>      {:phoenix_html, "~> 2.6"},
>      {:phoenix_live_reload, "~> 1.0", only: :dev},
>      {:gettext, "~> 0.11"},
>      {:cowboy, "~> 1.0"}]
>   end
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix_html/issues/93#issuecomment-228779246>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlboRmuG91_5Km_cbI7mtjIfH8_XMRks5qP-rrgaJpZM4I_MJT>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Never mind. I can confirm this bug by looking at Ecto source. It seems we
forgot to update v2.0 and only updated v1.1. Sorry about that, I will make
a new release shortly.

On Monday, June 27, 2016, José Valim <jose.valim@gmail.com> wrote:

> Those deps do not include the dependencies of your dependencies. "mix
> deps" will show it. If you have Ecto v2.0.1 it should be good to go. Can
> you put this application online on Github so I can investigate it too?
>
> On Monday, June 27, 2016, Ron Green <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I should have included my deps, which are all the latest I believe:
>>
>> defp deps do
>>     [{:phoenix, "~> 1.2.0"},
>>      {:phoenix_pubsub, "~> 1.0"},
>>      {:phoenix_ecto, "~> 3.0"},
>>      {:postgrex, ">= 0.0.0"},
>>      {:phoenix_html, "~> 2.6"},
>>      {:phoenix_live_reload, "~> 1.0", only: :dev},
>>      {:gettext, "~> 0.11"},
>>      {:cowboy, "~> 1.0"}]
>>   end
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/phoenixframework/phoenix_html/issues/93#issuecomment-228779246>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAAlboRmuG91_5Km_cbI7mtjIfH8_XMRks5qP-rrgaJpZM4I_MJT>
>> .
>>
>
>
> --
>
>
> *José Valimwww.plataformatec.com.br
> <http://www.plataformatec.com.br/>Founder and Director of R&D*
>
>

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by rgreenjr** [comment]
Thanks so much for the quick response José. I really appreciate all your work.

**Comment by josevalim** [comment]
2.0.2 is out, enjoy!
