### ISSUE TITLE
text_input with pattern attribute to support Unicode

### ISSUE THREAD

**Issue by sntran** [phoenixframework/phoenix_html#94]
I have some input that can contain Unicode characters, and I want to validate on them. Therefore, I use the `pattern` attribute to handle that. However, it looks like `text_input` renders the Unicode characters in the pattern.

## Steps to reproduce

```eex
<%= text_input f, :name, class: "mdl-textfield__input", pattern: "[A-Za-z0-9\u0080-\u00FF][A-Za-z0-9\u0080-\u00FF ]*" %>
```

## Expected output

```html
<input class="mdl-textfield__input" id="store_name" name="store[name]" pattern="[A-Za-z0-9\u0080-\u00FF][A-Za-z0-9\u0080-\u00FF ]**" type="text">
```

## Actual output

```html
<input class="mdl-textfield__input" id="store_name" name="store[name]" pattern="[A-Za-z0-9/-ÿ][A-Za-z0-9-ÿ ]*" type="text">
```

**Comment by chrismccord** [comment]
You need to double escape the unicode sequences:

    <%= text_input f, :name, class: "mdl-textfield__input", pattern: "[A-Za-z0-9\\u0080-\\u00FF][A-Za-z0-9\\u0080-\\u00FF ]*" %>
